### ISSUE TITLE
UseContract Function Uncaught Promise Reject Transaction

### ISSUE THREAD

**Issue by faillacec** [TrueFiEng/useDApp#1001]
**Describe the bug**
When using Contract Functions and this function is rejected in wallet, use contract error throw error of uncaught promise 

**To Reproduce**
ReactDOM.render(
  <DAppProvider config={{}}>
    <App />
  </DAppProvider>,
  document.getElementById('root')
)

const useAdminContractMethod = (methodName: string) => {
  const { state, send, events } = useContractFunction(
    AdminContract,
    methodName,
    { transactionName: methodName }
  );
  return { state, send, events };
};

const { state: EventMethodState, send: EventMethod } = useAdminContractMethod("methodFunctionName");

Call Function, open browser wallet (Metamask, Magic) and then reject transaction 
Expected Behavior 
- Manage error in state: Event MethodState 
Current Behavior 
- uncaught error in promise 

<img width="942" alt="Screen Shot 2022-10-12 at 10 35 25 AM" src="https://user-images.githubusercontent.com/97037379/195388767-fb7ab594-05d1-4702-84a4-5a7b82e9c34e.png">

<img width="1694" alt="Screen Shot 2022-10-12 at 10 35 40 AM" src="https://user-images.githubusercontent.com/97037379/195389136-a56d6fb1-83cf-48ea-aed4-ad83f37e96f0.png">

Browser: Chrome 
Wallets/Providers 
- Metamask 
- Magic Link
- WalletConnect
Network: Polygon-Mumbai 

**Software versions**
 - `useDapp` version 1.1.5
 - Package manager npm
 - Node version 14

**Additional context**

It work ok in useDapp version 1.0.12 when reject a transaction in wallet, useContractFunction state manage the error correctly

**Comment by rzadp** [comment]
Hey @faillacec

Thanks for reporting.
This issue has been fixed (but not released yet).
In the meantime, you can either:

1. Test the new dev version - `@usedapp/core@1.2.0-dev.b5d7950`
2. Wrap the `send` in a `try-catch`

Let me know how that goes.

**Comment by rzadp** [comment]
@faillacec That looks like it is coming from the extension.
So it happens when you reject - are there any other symptoms other than the error in developer console?
If there are no other symptoms, and the user is not impacted, then I think the error in the console can be ignored.

**Comment by faillacec** [comment]
Hi @rzadp, That was only an example to show you the error, the problem is that none notification is showed  when I call a function from contract using useContractFunction the  the state (const { state, send, events } = useContractFunction) never  is updated, it never change whether error or successfull or rejected (when rejected or error in transacction show uncaught error) never throw this error to catch
