### ISSUE TITLE
Switching Accounts in Metamask Mobile causes unstable behaviour

### ISSUE THREAD

**Issue by JayWelsh** [TrueFiEng/useDApp#1006]
**Describe the bug**
Using Metamask Mobile, if we connect to the website using useDapp (i.e. `Account A`), then switch to another account (i.e. `Account B`), a bug occurs once we make a wallet interaction (e.g. sign message). As far as I can tell, as soon as we run a function which causes wallet interaction, the `account` pulled from `useEthers()` will immediately glitch back to `Account A` (despite `Account B` being selected in Metamask Mobile), assuming we are signing a message, the Metamask Popup will actually show `Account B` when asking if you want to sign the message (so `account` via `useEthers` glitches back to the account which was selected when first connecting, despite the Metamask Mobile dialogue showing `Account B`, furthermore, upon signing the message and running an `ecrecover` on the signed message, we will see that it was signed by `Account A`).

**To Reproduce**
For the sake of this description, let's imagine a user has `Account A` and `Account B` stored within the same Metamask Mobile instance. 

1. User initially connects to a website using `Account A`
2. User switches to `Account B` (bug is now locked and loaded, ready to show)
3. User tries to sign a message using `Account B`
4. `account` from `useEthers` glitches back to `Account A`
5. Metamask Mobile confirms if user wants to sign message using `Account B`
6. `ecrecover` on the signed message shows that it was signed by `Account A`, instead of `Account B`

**Software versions**
 - `useDapp` version: `1.1.5`
 - yarn
 - Node version: `v14.16.0`

**Additional context**

Video demonstration using https://example.usedapp.io/ - unfortunately the example website isn't mobile friendly but I've done my best to add some basic annotations as to what is happening

https://user-images.githubusercontent.com/14224459/196252756-9608d169-6f68-48ef-892c-3ee85727b190.mp4

**Comment by rzadp** [comment]
@JayWelsh That's metamask mobile on ios or android?
We'll be looking into it, please share any more relevant info you could think of.

**Comment by JayWelsh** [comment]
Hi @rzadp, thanks a lot! This was on Android :)

**Comment by JayWelsh** [comment]
Just some thoughts, It seems like on MetaMask's side, the desktop extension handles account switching a bit differently. For example when switching to an account which hasn't yet been connected to the frontend, it doesn't actually switch the `account` of `useEthers`, one needs to open their MetaMask first and "connect" the new account to the frontend before it will change the value of `account` from `useEthers`.

MetaMask mobile seems to handle things differently to this, for example when switching to a wallet address which hasn't been connected to the frontend yet, it just automatically updates the `account` from `useEthers`, it seems like MetaMask mobile doesn't have quite the same concept of "connected" and "not connected" wallet addresses within a MetaMask profile. It seems to just automatically connect whichever wallet address you switch to.

That being said, even if I switch to an address which I have already allowed to connect to the frontend, it still reverts to the first account that I connected to the frontend with as soon as I try to sign a message.

i.e. if I connect to the site with Account A, and switch to Account B (even if Account B is allowed to connect to the site), then it still reverts back to Account A, as soon as I try to sign a message.

I imagine that this could potentially impact the sign in with Ethereum functionality. In my case I am working with a dApp which requires a lot of message signing which is how I noticed this behaviour.

Sorry if none of this is useful info but just thought I'd put it here in case it helps @rzadp 

Thanks a lot 💯

**Comment by rzadp** [comment]
Hey @JayWelsh 

> it seems like MetaMask mobile doesn't have quite the same concept of "connected" and "not connected" wallet addresses within a MetaMask profile. It seems to just automatically connect whichever wallet address you switch to.

Looks like it, I see it that way too.

I could not reproduce the problem on iOS:

https://user-images.githubusercontent.com/12039224/196915757-4150dbc3-ef43-4f83-af2d-e015a8f14b6b.mov

We'll try to investigate further on Android.

**Comment by yivlad** [comment]
It also works for android for me.

Metmask mobile version: v5.8.1(986)
Android version: 12

https://user-images.githubusercontent.com/52505649/196925435-6cf6aa38-3c43-4036-8778-06494d3f2ed8.mp4

**Comment by rzadp** [comment]
The preview we used is https://6351200f5f312307f46e637a--usedapp-example.netlify.app/

**Comment by JayWelsh** [comment]
Hi guys, this was my bad, my device storage was full and wasn't allowing MetaMask to update. Freed up space to make sure MetaMask mobile was updating and now I can't replicate my issue anymore. Terribly sorry for wasting your time @yivlad & @rzadp

**Comment by rzadp** [comment]
@JayWelsh No problem, I'm glad we worked it out :)
