### ISSUE TITLE
Adding overrides object to useCall hook, breaks and throws error

### ISSUE THREAD

**Issue by gsteenkamp89** [TrueFiEng/useDApp#1011]
**Describe the bug**
When adding `overrides` object to the `useCall` hook, there is an error thrown. Not adding the overrides produces the desired result, but I am unable to add a "from" address to the call.

This works:
```typescript
  const { account } = useEthers();
  const { value, error } =
    useCall(
      account && {
        contract: reignTokenContract,
        method: 'getStakingAmount',
        args: [account],
      }
    ) ?? {};
```

This does not. It returns undefined.
```typescript
  const { account } = useEthers();
  const { value, error } =
    useCall(
      account && {
        contract: reignTokenContract,
        method: 'getStakingAmount',
        args: [account, { from : account }],
      }
    ) ?? {};
```

The error in console:

**_Invalid contract call: 
address=0x07f20dAbe6DA77858b81e2b08c555477268bd92A method=getStakingAmount args=0xC54070dA79E7E3e2c95D3a91fe98A42000e65a48,[object Object]_** 

**To Reproduce**
call a view function using useCall. Check resuult. then call again with overrides object `{ from : "SOME_ADDRESS" }`

**Software versions**
 - useDapp v1.1.5
 - Package manager  YARN
 - Node version v16.15.1

**Comment by jakvbs** [comment]
Hi @gsteenkamp89, what is the purpose of adding the overrides object in this case?

**Comment by gsteenkamp89** [comment]
> Hi @gsteenkamp89, what is the purpose of adding the overrides object in this case?

In my case, the view function (somewhat erroneously imo) uses `msg.sender` while performing some sort of computation. 
And not having a from address specified means the result of the calculation is incorrect. Consider this example:

```solidity
    function getNetAmount(address user) external view returns (uint256 memory _amount) {
        uint256 _amount = amounts[user].totalAmount - amounts[msg.sender].expenses
        return _amount;
    }
```

Here the author of the contract should've used `user` instead of `msg.sender`, but that's another issue entirely.
My point is shouldn't we always be able to add override object to any contract interaction whether it's a write or just a read? I don't believe this is a limitation of multicall, but I might be wrong...

**Comment by jakvbs** [comment]
I realized that this problem has occurred before and was raised [here](https://github.com/TrueFiEng/useDApp/issues/897#issuecomment-1193888691). Unfortunately, we currently know that it cannot be done if the call is going through Multicall. The only solution at this point is to call the method directly on the contract instance like in this example:
```tsx
  const [balance, setBalance] = useState('0')
  const { account, library } = useEthers()
  const contract = new Contract(wethAddress, wethInterface, library)

  useEffect(() => {
    const getBalance = async () => {
      if (account) {
        const currentBalance = await contract.balanceOf(account, {
          from: account,
        })
        setBalance(currentBalance.toString())
      }
    }
    void getBalance()
  }, [account, contract])
```

You can also use `useBlockNumber` hook which is available in `@usedapp/core` and pass its result to the dependency array in `useEffect` hook to make sure that the balance is updated on every block.

**Comment by gsteenkamp89** [comment]
> I realized that this problem has occurred before and was raised [here](https://github.com/TrueFiEng/useDApp/issues/897#issuecomment-1193888691). Unfortunately, we currently know that it cannot be done if the call is going through Multicall. The only solution at this point is to call the method directly on the contract instance like in this example:
> 
> ```tsx
>   const [balance, setBalance] = useState('0')
>   const { account, library } = useEthers()
>   const contract = new Contract(wethAddress, wethInterface, library)
> 
>   useEffect(() => {
>     const getBalance = async () => {
>       if (account) {
>         const currentBalance = await contract.balanceOf(account, {
>           from: account,
>         })
>         setBalance(currentBalance.toString())
>       }
>     }
>     void getBalance()
>   }, [account, contract])
> ```
> 
> You can also use `useBlockNumber` hook which is available in `@usedapp/core` and pass its result to the dependency array in `useEffect` hook to make sure that the balance is updated on every block.

This is exactly what I ended up doing 😅 
I didn't realise this was a multicall issue. I really appreciate the feedback, thank you! 👍
