### ISSUE TITLE
alchemyapi 429 error

### ISSUE THREAD

**Issue by ugurcanomur** [TrueFiEng/useDApp#1016]
**Describe the bug**
i am getting 429 error from  https://eth-mainnet.alchemyapi.io endpoint when i wrap my application DAppProvider

**Software versions**
 - `useDapp` version - 1.2.0
 - Package manager - 6.14.16
 - Node version - v14.19.1

**Additional context**
when i check example website, i can see same errors on console tab.

**Comment by jakvbs** [comment]
That's probably because the example app uses default providers and they very often throw some random errors. This should not be a problem if you use a provider with your own Infura or Alchemy id.

**Comment by jakvbs** [comment]
Hi @ugurcanomur, could you please send your app config?

**Comment by jakvbs** [comment]
It seems to me that the reason for the appearance of this error is use of default provider. It very often causes some problems. You can try instead to use provider with your custom Infura api key like this: 
```tsx
const config = {
    readOnlyChainId: Mainnet.chainId,
    readOnlyUrls: {
        [Mainnet.chainId]: 'https://mainnet.infura.io/v3/YOUR-API-KEY',
        56: "https://bsc-dataseed1.binance.org/",
    },
};
```
and the problem should disappear.

**Comment by ugurcanomur** [comment]
hey @jakvbs your solution worked. problem been fixed for me, thanks a lot :)
