### ISSUE TITLE
notify of transaction waiting to be signed

### ISSUE THREAD

**Issue by sirpy** [TrueFiEng/useDApp#1027]
I think this state should also be added to notifications, for example this would allow to create a global modal to be shown while the UI is waiting for the user to sign the tx on his wallet
https://github.com/TrueFiEng/useDApp/blob/14c271f0a744038be53c3326610a7df4c9ca21e4/packages/core/src/hooks/usePromiseTransaction.ts#L95

**Comment by sirpy** [comment]
@jakvbs @rzadp anyone?

**Comment by rzadp** [comment]
@sirpy  I think this is a valid suggestion.
It might end up in notifications or transactions.

However, this might be a breaking change for existing apps displaying transactions/notifications - they might not handle a new type of transaction/notification as expected without changing their code.

We will look into this, thanks for suggesting. Also contributions are welcome.

**Comment by sirpy** [comment]
#1046 @rzadp
