### ISSUE TITLE
build command for vercel? `help needed`

### ISSUE THREAD

**Issue by RohitKS7** [TrueFiEng/useDApp#1031]
Hey, I'm trying to deploy my website on Vercel but this commands for project building is not working ( Vercel UI)
1. `yarn react-app:build`
2. `yarn build`
3. `yarn workspace @my-app/react-app build`

After that I tried to deploy with Vercel CLI

The problem I'm facing is, I'm confused! 
which directory to use "as output", "as root" and should I use 'create-react-app' or others as framework while deploying since it consists contract and more node_module outside of react-app folder.

Can anyone guide me to what is the right path to deploy it.

**Comment by rzadp** [comment]
@RohitKS7 hey, thanks for reaching out.
It seems like it is not related to useDApp so I will close the issue, but still we'd like to help.
Is your code public? Maybe hop on our discord and ask again.

**Comment by RohitKS7** [comment]
Yes my code is public. And I think it is related to useDapp somehow since its a complex framework and how which folder to use for deployment is very confusing + command.
