### ISSUE TITLE
Fallback does not have send() method

### ISSUE THREAD

**Issue by afa7789** [TrueFiEng/useDApp#1032]
**Describe the bug**
I upgrade from the version 1.1.5 to the newer one 1.2.2 and in the parts of the code that I used `Web3Ethers` I'm unable to keep using due to an upgrade in the code of TrueFiEng. ( which I needed to upgrade to get the newer arbitrum chain goerli )

**To Reproduce**
make a send with the library in the ` useWeb3()` function: 
![image](https://user-images.githubusercontent.com/26887703/203161592-e676abaa-d58a-42bf-95ee-4d6817eaa07f.png)

**Software versions**
 - `useDapp` version (installed version of `@usedapp/core`): 1.2.2
 - Package manager : yarn 3,1,9
 - Node version (`node --version`): v16.14.2

**Additional context**

in the previous version we didn't had fallback provider in useWeb3():
![image](https://user-images.githubusercontent.com/26887703/203161920-5b42c9f2-df6a-4def-999d-fe0aab6bc825.png)
Previous:
![image](https://user-images.githubusercontent.com/26887703/203161890-33eb6851-1f21-4ce0-843c-2926ed82a763.png)
Current:
![image](https://user-images.githubusercontent.com/26887703/203161990-cf8ee411-55c6-44ed-b3a2-7bcedf28e563.png)

Fallback does not have send function. I'm not sure how to workaround or deal with it yet. Is there a way or suggestion you guys could make ? ( What I planned on doing was forking and removing fallback )

**Comment by afa7789** [comment]
For the time being I reverted back the Version to where the arb goerli was added. But when further needing an upgrade this will remain as an issue.

**Comment by rzadp** [comment]
@afa7789 

Try this:

```ts
if (library && 'getSigner' in library) {
    library.send(xxx)
}
```

With this code, you ensure that the `library` actually is NOT a fallback provider, and can use `send`.

Let me know if that help :)
