### ISSUE TITLE
[Feature Request] ChainId for NOVA: 42170?

### ISSUE THREAD

**Issue by andreibadea20** [TrueFiEng/useDApp#1039]
Hello guys!
Sorry to bother you, but I have one question: Any way to add Arbitrum Nova id: 42170 in ChainId ?

**Comment by yivlad** [comment]
Hey, please follow [this](https://usedapp-docs.netlify.app/docs/guides/connecting/custom%20chains/) tutorial for adding a custom chain to useDApp.
