### ISSUE TITLE
ChainId for Flare Network

### ISSUE THREAD

**Issue by MkDev11** [TrueFiEng/useDApp#1066]
Hi there, currently, I am building a dApp for users to delegate their FLR tokens on the Flare network, unfortunately, useDApp library doesnt provide a chainId for Flare network.
Could you please let me now the best way to solve this issue?

**Comment by yivlad** [comment]
Hey @MkDev11, you can create a PR with the Flare network to this repo and we'll merge it. The example PR which adds a new chain is [here](https://github.com/TrueFiEng/useDApp/pull/1017).
