### ISSUE TITLE
Not found the chainId for Flare network 

### ISSUE THREAD

**Issue by MkDev11** [TrueFiEng/useDApp#1077]
**Describe the bug**
I am trying to build a dApp on Flare network, but I can't find the chainId. How can I solve the issue?

**Comment by pawelpolak2** [comment]
The flare network was added recently and is not released yet. You can use the dev version (`pnpm add @usedapp/core@dev`) to access it like this:
`
import { ChainId } from '@usedapp/core'
console.log(ChainId.Flare) // 14
`
