### ISSUE TITLE
Having issues in import 

### ISSUE THREAD

**Issue by Haris565** [TrueFiEng/useDApp#1081]
Getting this error when i am trying to import from @usedapp/core
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/@usedapp/core/dist/esm/src/hooks/useEthers.js:1:0
Module not found: Package path ./lib/utils is not exported from package /Users/haris/usedapp/node_modules/ethers (see exports field in /Users/haris/usedapp/node_modules/ethers/package.json)

Import trace for requested module:
./node_modules/@usedapp/core/dist/esm/src/hooks/index.js
./node_modules/@usedapp/core/dist/esm/src/index.js
./src/pages/_app.tsx

**Comment by tiagofs** [comment]
I'm having the same issue. 
This is happening with the new version of ethers (v6).
Going into the package.json and downgrading ethers to 5.6.9 solved it.

**Comment by yivlad** [comment]
Fixed in #1087
