### ISSUE TITLE
Add Caching/Limits to Contract Calls

### ISSUE THREAD

**Issue by kamescg** [TrueFiEng/useDApp#156]
With `useContractCall` and `useContractCalls` it's mentioned the data is updated every block.

This approach can get expensive when paying for a node service (Infura/Alchemy)

Any discussions for adding caching or limiting fetches?

Personally, I've been using react-query to wrap my contract call and had a lot of success.

Would be great to add at a minimum the ability to limit refetches and/or also the ability cache requests and only refetch if certain parameters in the state have been met i.e. a certain function has been called/broadcast/confirmed or another state change in the application.

**Comment by marekkirejczyk** [comment]
The whole point is to provide good UX and show current data. 
Therefore I suspect most applications requires to refresh on every block.

Note that:
- Data is cached between the blocks. 
- Only data visible to the user is included in the mulitcall (as each hooks add/removes calls on component mount/unmount).

Some ideas for the features I could see at later stages of development:
- add a config to refresh every n-blocks 
- distinguish between immutable (e.g. token name) and refreshable data (e.g. user balance)
- paginate multicall (original Maker library paginates by 500 calls)

**Comment by kamescg** [comment]
You can provider good UX without refetching stale data. Depending on the application it could the case where most data is static, whether it's immutable or not.

It could even be a separate hook, so that expected behavior can be more easily managed.

- add a config to refresh every n-blocks
- distinguish between immutable (e.g. token name) and refreshable data (e.g. user balance)

those both sound like good place to start. personally I would use a method to manually refetch before those though, so the application has more control of when to fetch data.

**Comment by marekkirejczyk** [comment]
Interesting, we could add `CallOptions` with `refreshFrequency` parameter:
```ts
const wethBalance = useContractCall({
  abi: wethInterface,
  address: '0xA243FEB70BaCF6cD77431269e68135cf470051b4',
  method: 'balanceOf',
  args: [account], {
    refreshFrequency: eachBlock
  });
```

With options like:
`eachBlock`, `everyBlock(n)`, `never`

Application configuration could include `defaultRefreshFrequency`.

`eachBlock` could be a function, returns true or false for given multicall and block.

**Comment by kamescg** [comment]
That sounds like a great place to start.

BTW great library! Really liking it so far - very easy to use.

**Comment by quagliero** [comment]
Just wondering if there has there been any progress on this?

**Comment by 0xCryptodd** [comment]
> Just wondering if there has there been any progress on this?

Same - this would be really useful. For immutable data (token name, symbol, decimals), makes no sense to query that data every block. Can get very expensive

**Comment by charlesAuthentik** [comment]
Any progress on this?? Would love to have this feature!! Thanks
