### ISSUE TITLE
Cannot use `useContractFunction` in NextJS

### ISSUE THREAD

**Issue by bitfede** [TrueFiEng/useDApp#232]
Hello guys! I am opening this issue after posting on https://github.com/EthWorks/useDApp/pull/207#issuecomment-847014624 

Unfortunately even after following the instructions on https://usedapp.readthedocs.io/en/latest/guide.html#executing-contract-function I'm getting that signer error

<img width="1082" alt="Screen Shot 2021-05-24 at 5 24 47 PM" src="https://user-images.githubusercontent.com/15684622/119409267-0a217780-bcb5-11eb-96c1-1dba70f3ed1b.png">

So I wanted to ask what are the best practices when using this function with NextJS, can you provide with an example or a suggestion?

Thank you very much!

**Comment by Szymx95** [comment]
Hello,

It seems as it may a problem with context providers

Have you wrapped your app in DAppProvider ?

```ts
    <DAppProvider config={config}>
      <App />
    </DAppProvider>
```

Also have you tried a getting started exampled [here](https://usedapp.readthedocs.io/en/latest/getting-started.html) ?

**Comment by marekkirejczyk** [comment]
We are not experts on NextJs, but make sure useDApp part is not rendered on server side.

**Comment by marekkirejczyk** [comment]
Related issue:
https://github.com/EthWorks/useDApp/issues/120

**Comment by crazyrabbitLTC** [comment]
if you're doing it on NextJS, you'll probably need to first check that `window.ethereum` exists, or maybe even just `window` is enough. When NextJS is bundling server side, there won't be any "window" available and that will break your web3 functionality.

**Comment by quagliero** [comment]
Hi @bitfede - I'm building the NFTX v2 app with nextjs and useDapp so feel free to ping me if you have any questions or issues. Do you have a snippet of the surrounding code? You'll need to make sure this isn't running inside any of the server side functions (getStaticProps etc) as useDapp requires access to the context which runs client side.

**Comment by zakatz** [comment]
Has anyone made any progress on useDapp with NextJS?

**Comment by mj426382** [comment]
If problem is still alive check out this repo https://github.com/ChangoMan/nextjs-ethereum-starter.
Here is simple example how to use useDapp with next.js
