### ISSUE TITLE
Type Error on useContractFunction

### ISSUE THREAD

**Issue by stevennevins** [TrueFiEng/useDApp#263]
I'm writing a hook for a contract, and there is type error when I run tests with @testing-library/react-hooks.  This useContractFunction is looking for the contract type from the @ethersproject/contracts installed in core even though it should be the one installed in my repo.  It causes a typing lint message to pop up, works when testing in the browser, but when testing with @testing-library/react-hooks will fail the test due to the type mismatch.

This fixes the typing error, but not sure if it's the recommended way to solve the mismatch

import { Contract } from '@ethersproject/contracts' ->  import { Contract } from '@usedapp/core/node_modules/@ethersproject/contracts'

**Comment by ccashwell** [comment]
Same here, type error when using a the ethers library directly.

**Comment by lcamargof** [comment]
Just ran into this, if you are using the `ethers` package, try to match it with the version installed in useDapp, currently is `5.4.1` that fixed my typing issue

**Comment by koirikivi** [comment]
I got a similar error:

```
  Types of property '_runningEvents' are incompatible.
    Type '{ [eventTag: string]: RunningEvent; }' is not assignable to type '{ [eventTag: string]: RunningEvent; }'. Two different types with this name exist, but they are unrelated.
      'string' index signatures are incompatible.
        Type 'RunningEvent' is not assignable to type 'RunningEvent'. Two different types with this name exist, but they are unrelated.
          Types have separate declarations of a private property '_listeners'.  TS2345

    52 |     ) ?? [];
    53 |     const {state, send} = useContractFunction(
  > 54 |         fastbtcBridge,
       |         ^
    55 |         'transferRBTCtoBTC'
    56 |     );
    57 |
```

`@usedapp/core` 0.4.7.
Tried ethers 5.4.1, 5.4.0 and 5.1.4.

**Comment by igormorgado** [comment]
Same issue @usedapp/core 0.5.1 and ethers 5.4.0.

**Comment by kathamas** [comment]
I got a similar error:
```

    Types of property '_runningEvents' are incompatible.
    Type '{ [eventTag: string]: RunningEvent; }' is not assignable to type '{ [eventTag: string]: RunningEvent; }'. Two different types with this name exist, but they are unrelated.
      'string' index signatures are incompatible.
        Type 'RunningEvent' is not assignable to type 'RunningEvent'. Two different types with this name exist, but they are unrelated.
          Types have separate declarations of a private property '_listeners'.  TS2345

    26 | 
    27 |     const { send: approveErc20Send, state: approveErc20State } =
  > 28 |         useContractFunction(erc20Contract, "approve", {
       |                             ^
    29 |             transactionName: "Approve ERC20 transfer",
    30 |         })
```

@usedapp/core 0.5.4  ethers version: 5.5.1

**Comment by kathamas** [comment]
> I got a similar error:
> 
> ```
>   Types of property '_runningEvents' are incompatible.
>     Type '{ [eventTag: string]: RunningEvent; }' is not assignable to type '{ [eventTag: string]: RunningEvent; }'. Two different types with this name exist, but they are unrelated.
>       'string' index signatures are incompatible.
>         Type 'RunningEvent' is not assignable to type 'RunningEvent'. Two different types with this name exist, but they are unrelated.
>           Types have separate declarations of a private property '_listeners'.  TS2345
> 
>     52 |     ) ?? [];
>     53 |     const {state, send} = useContractFunction(
>   > 54 |         fastbtcBridge,
>        |         ^
>     55 |         'transferRBTCtoBTC'
>     56 |     );
>     57 |
> ```
> 
> `@usedapp/core` 0.4.7. Tried ethers 5.4.1, 5.4.0 and 5.1.4.

I solved this problem.
You  remove the folder @ethersproject/contracts in node_modules or put it in a different folder from @usedapp.

**Comment by brunoalano** [comment]
@kathamas solution worked for me

**Comment by whoa174** [comment]
I ran into the same error. How to remove the folder @ethersproject in @usedapp/core > node_modules?

**Comment by uzair011** [comment]
You should try to replace this import:
    `import { Contract } from "@ethersproject/contracts"`

**for this:**
`    import {Contract} from '@usedapp/core/node_modules/@ethersproject/contracts'`

**Comment by edithcoin** [comment]
@uzair011 solution seems to work for me. Removing the folder did not work.

Are there any good *working* examples of useDapp and React programs? Every single thing I've found doesn't compile, including the example code from the official docs.

**Comment by albertoramires** [comment]
For anyone having this issue, follow this guide: https://usedapp-docs.netlify.app/docs/Guides/Reading/Typechain
And make sure all the ethers package versions match useDapp, if you use the ones here it should work: https://github.com/TrueFiEng/useDApp/blob/f5c7a3cf394bc3c6907d7252d04987a59019ac3b/packages/example/package.json
Didn't dig into this, but if I add ethers to my packages I get this error again, if I don't include it usedapp includes it (?) and it works just fine, even if I include the same version usedapp is using I get this error.

**Comment by rzadp** [comment]
Me and @yivlad are thinking about changing ethers to be a peer dependency of usedapp. It might fix issues like this, but introduce a little overhead for users.
