### ISSUE TITLE
Integration with NextJS

### ISSUE THREAD

**Issue by damianlluch** [TrueFiEng/useDApp#271]
Hello, does this library support NextJS?

Thanks

**Comment by damianlluch** [comment]
I try with this library en an NextJS project and I get this error.

Module not found: Can't resolve 'react/jsx-runtime'


in pages/_app.js

I writed this code

![image](https://user-images.githubusercontent.com/1463804/123075937-f59ddf80-d418-11eb-97a7-3a353b578686.png)


and in my component, I writed this.

![image](https://user-images.githubusercontent.com/1463804/123076026-09494600-d419-11eb-980f-c870ce1fa2e7.png)

**Comment by quagliero** [comment]
@damianlluch inside your Providers.js you’re not rendering `children` inside the DAppProvider.

**Comment by jjperezaguinaga** [comment]
@damianlluch Checkout  @ChangoMan 's [branch](https://github.com/austintgriffith/scaffold-eth/tree/nextjs-typescript) inside @austintgriffith's [Scaffold ETH](https://github.com/austintgriffith/scaffold-eth/) repo, it showcases `useDApp` and `next.js`

**Comment by mj426382** [comment]
If problem is still alive check out this repo https://github.com/ChangoMan/nextjs-ethereum-starter.
Here is simple example how to use `useDapp` with next.js
