### ISSUE TITLE
WalletConnect integration - any idea guys?

### ISSUE THREAD

**Issue by eliotmess** [TrueFiEng/useDApp#292]
Hello,

I'm struggling with WalletConnect integration in my useDApp based app. Any of you tried it?
The thing is to change provider -> https://docs.walletconnect.org/quick-start/dapps/web3-provider

Do you think it's possible with useDApp?

**Comment by niconiahi** [comment]
would be nice to be able to do something like this (see example). That way, we wouldn't lose the good error handling `useDapp` already does on the `activateBrowserWallet` method. This new method, in essence, would be a flexible `activateBrowserWallet`, which is tightly attached to `Injected` _web3-react connector_

```tsx
import { useEthers } from '@usedapp/core'
import { WalletConnectConnector } from '@web3-react/walletconnect-connector'

const walletconnect = new WalletConnectConnector({
  rpc: { ...yourconfig },
  qrcode: true
})

const WalletConnectionSelection = () => {
    const { activateWallet } = useEthers()
    
    activateWallet(walletconnect)
}
```

**Comment by RongxinZhang** [comment]
That would be dope. Could some create some technical notes and estimates on how long something like this could take. This could be help me or others to see if there is enough time to contribute. I think the biggest challenge is just setting up the local testing/development environment. @tt-marek @niconiahi

**Comment by mj426382** [comment]
https://usedapp-docs.netlify.app/docs/Guides/Connecting/Wallet%20Connect
