### ISSUE TITLE
useContractCall gives shuffled responses with array of structs

### ISSUE THREAD

**Issue by karlptrck** [TrueFiEng/useDApp#299]
useContractCall gives shuffled responses from contract function that returns an array of structs. Values get assigned inappropriately. 

Sample Code:

```
mapping(address => A[]) arrayOfStructs;

struct A {
 uint x;
 uint y;
 uint z;
}

function getStructs(address acct) external view returns (A[] memory items) {
 return arrayOfStructs[account];
}
```

When calling the getStructs function via useContractCall, the first item gets the right values assigned while the succeeding items gets shuffled value assignment. A.x sometimes get the value of A.z and so on.

"@usedapp/core": "^0.4.0",

Thanks

**Comment by mj426382** [comment]
`useContractCall` is deprecated, try to use `useCall` instead.
