### ISSUE TITLE
Add links to extensions in docs

### ISSUE THREAD

**Issue by aspiers** [TrueFiEng/useDApp#301]
Thanks a lot for this extension, it looks awesome!

The docs claim that the extension is not yet available from the Chrome Web Store or Firefox Add-ons:

https://github.com/EthWorks/useDApp/blob/60807e44aee173f96ae9c4d4f9fa6dac617a3ab8/docs/source/developer-tools.rst#L11-L12

but https://medium.com/ethworks/introducing-usedapp-developer-tools-d52fe77e8230 offers links for both.  That Medium article looks like it is from a legitimate source, so I assume there is no foul play here, but given that uploading malware extensions to these stores is a well-known browser attack vector which has been used in the past, it would be reassuring to update the docs to confirm that those are the correct extension links!  Thanks again :-)

**Comment by tt-marek** [comment]
Docs updated:
https://usedapp.readthedocs.io/en/latest/developer-tools.html#installation

**Comment by aspiers** [comment]
Thanks but why not link to the two stores at https://usedapp.readthedocs.io/en/latest/developer-tools.html#installation instead of just listing them?

**Comment by aspiers** [comment]
To be clear: the main concern is accidentally downloading the wrong extension which turns out to be malicious.  Without links to the correct extensions, not only does the reader of these docs have to manually search a store for the extension, but even once it's found, they have no confidence that the one they found is the right one.

**Comment by tt-marek** [comment]
Fair point - reopening

**Comment by mj426382** [comment]
Here you can find our new docs with developer tools tutorial:
https://usedapp-docs.netlify.app/docs/Guides/Developer%20Tools
