### ISSUE TITLE
Add arbitrum support?

### ISSUE THREAD

**Issue by jontonsoup** [TrueFiEng/useDApp#324]
seems like the multi call address is:

            [42161]: "0xd130B43062D875a4B7aF3f8fc036Bc6e9D3E1B3E",

https://discord.com/channels/585084330037084172/859511259183448084/882596393552859157

**Comment by SafeEarn** [comment]
Thanks for trying to help, but what even is that discord link? I cannot seem to find it anywhere :|

**Comment by jontonsoup** [comment]
I would not use the link as the source of truth. Here is a screenshot

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/845636/134242961-4a1513da-e0c6-4bf9-af8c-0a2cabf88439.png">

Here is the link they link to: https://github.com/0xsequence/sequence.js/tree/master/packages/multicall

That is from the arbitrum discord channel.

**Comment by jontonsoup** [comment]
Sorry I don’t have it working. That’s why I created the issue :)

**Comment by osengaa10** [comment]
Has anyone figured this out? I too am getting a generic `MetaMask - RPC Error: Internal JSON-RPC error`
