### ISSUE TITLE
Improve Docs of useEthers hook

### ISSUE THREAD

**Issue by LuisHPorras** [TrueFiEng/useDApp#332]
### Description
In the [useEthers hook](https://usedapp.readthedocs.io/en/latest/core.html#useethers) add the following parameter:
connector: AbstractConnector - current connector

Also as a note I suggest adding this text to the general description, to help migrating from web3-react to useDapp: 
This hook returns the whole object returned by the useWeb3React hook of the [web3-react repo](https://github.com/NoahZinsmeister/web3-react) plus the activateBrowserWallet function.

**Comment by mj426382** [comment]
Check our new docs:)
https://usedapp-docs.netlify.app/docs/API%20Reference/Hooks
