### ISSUE TITLE
Migrate to Multicall2 instead of Multicall

### ISSUE THREAD

**Issue by maraoz** [TrueFiEng/useDApp#334]
I had some problems when 1 of the calls in a multicall fails, and apparently that's fixed in Multicall2:

> Multicall2 is the same as Multicall, but provides addition functions that allow calls within the batch to fail. Useful for situations where a call may fail depending on the state of the contract.

https://github.com/makerdao/multicall#multicall2-contract-addresses

Consider using Multicall2 in useDapp. I can even try sending a pull request myself if you agree with the "upgrade"

**Comment by devloper-eth** [comment]
+1 on this. I spent hours debugging an error caused by Multicall's v1 inability to handle individual call failures. The resulting error message we received was `MetaMask - RPC Error: BlockReEmitMiddleware - retries exhausted` describing a symptom but not the root cause.
