### ISSUE TITLE
eip-1193 - Invalid contract call: address=.... "MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead."

### ISSUE THREAD

**Issue by phutngo** [TrueFiEng/useDApp#342]
I have a React front end that looks like it is working perfectly with my smart contract but I'm getting these warnings on page load.

`MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.`

`MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.`

`MetaMask: The event 'networkChanged' is deprecated and may be removed in the future. Use 'chainChanged' instead.`

`For more information, see: https://eips.ethereum.org/EIPS/eip-1193`

Is this an issue with useDapp? Any tips to point me ion the right direction?

**Comment by jhirn** [comment]
Unfortunately it's downstream in web3-react. There are several issues there regarding this matter.

**Comment by mj426382** [comment]
Using Web3react with useDapp may lead to unexpected behaviour.
