### ISSUE TITLE
too many `eth_chainId` calls

### ISSUE THREAD

**Issue by maraoz** [TrueFiEng/useDApp#356]
I noticed the following in my infura stats:
![image](https://user-images.githubusercontent.com/287189/136646295-fb57bf37-274d-41ee-a31a-da8117d2b559.png)

Googling around I found that it [seems to be related to JsonRpcProvider](https://github.com/ethers-io/ethers.js/issues/901), from which `Web3Provider` inherits. Is there any way to use a custom ethers `Provider` in useDapp? both `StaticJsonRpcProvider` and `InfuraProvider` seem to solve this problem, but it was not clear if this could be changed as a useDapp user.

Thanks!

**Comment by maraoz** [comment]
My bad, it was a problem with a script that was using the same infura id, not useDapp. Closing

**Comment by maraoz** [comment]
Reopening, I moved scripts to another infura id and I'm still getting one `eth_chainId` call for every call in my dapp. We should probably investigate this further, as it could mean extra calls and delays for all dapps using useDApp.

**Comment by jhirn** [comment]
Also very curious about this. Will do some digging on my own or at least try to apply the patch referred to in https://github.com/ethers-io/ethers.js/issues/901

Feel like this should be an easy if not detectable config change.
