### ISSUE TITLE
Is it possible to use a custom provider/library for useContractCall?

### ISSUE THREAD

**Issue by cryptodapp** [TrueFiEng/useDApp#359]
As the title suggest, how do we use a custom library for contract call?

In cases where the user is connected to a different chain but my contract lives on a different network, the useContractCall fails. Thanks

**Comment by noobshow** [comment]
Cool solution over there

> I wrote a custom hook in the style recommended by useDapp to query contract events. I had to drop down into ethers.js and connect my own signer to the contract. I'm not connecting to a different provider/signer but you could see here how to customize an ethers.js call in in a useDapp'y way.
> 
> Just pass your own provider instead of the one returned by `useEthers` and call your Contract method directly.
> 
> ```ts
> import { Contract, Event } from '@ethersproject/contracts'
> import { useEffect, useState } from 'react'
> import { useEthers } from '@usedapp/core'
> 
> export function useContractEvents (contract: Contract | null) {
>   const [contractEvents, setContractEvents] = useState<Array<Event>>([])
>   const { library } = useEthers()
> 
>   useEffect(() => {
>     async function fetchEvents (contract: Contract) {
>       if (library) {
>         try {
>           const filter = contract.filters.Mint()
>           const connectedContract = contract.connect(library)
>           const result = await connectedContract.queryFilter(filter)
>           setContractEvents(result)
>         } catch (error) {
>           setContractEvents([])
>         }
>       }
>     }
> 
>     if (contract) {
>       fetchEvents(contract)
>     }
>   }, [contract, library])
> 
>   return contractEvents
> }
> ```
> 
> Hope it helps.
