### ISSUE TITLE
[Bug] No events returned from useContractFunction hook if contract address is lower-case

### ISSUE THREAD

**Issue by josh-richardson** [TrueFiEng/useDApp#363]
Currently, if you create a `useContractFunction` hook likeso:

```
const CONTRACT = new Contract('0x_some_valid_lowercase_address', CONTRACT_ABI);
const { state, send, events } = useContractFunction(CONTRACT, 'safeMint', { transactionName: 'Mint' });
```

No events will come through as https://github.com/EthWorks/useDApp/blob/master/packages/core/src/hooks/useContractFunction.ts#L37 filters the log address against the contract address in a case-sensitive manner.

Happy to submit a PR to fix this, just unsure if it should be normalized in the constructor or at the point of comparison.

**Comment by Crypt0-Bear** [comment]
I just noticed this as an issue while looking for a different issue. Passing it as a lowercase seems to emit no event.

**Comment by rzadp** [comment]
This should be fixed now.

https://github.com/TrueFiEng/useDApp/blob/0fd73d1dbed00a7d7d915e0f89f81333704bf0cd/packages/core/src/hooks/useContractFunction.ts#L48
