### ISSUE TITLE
useContractCall and Contract with a function that call another Contract

### ISSUE THREAD

**Issue by unzsnu** [TrueFiEng/useDApp#364]
Hi there, i'm using **useContractCall** to get values from a solidity contract.
I've implemented several functions, but only those that inside invoke another Contract can't be resolved with a value.
Using **useContractFunction**, with the very same Contract, i can resolve those values, but the status is 'Fail' and an error message about 'transaction.view() is not a function' was thrown
State 'Fail' makes sense, because those functions are views, and nothing has to be mined.
Any clues?

**Comment by tt-marek** [comment]
Not sure if I follow, could you share a sample code (js & sol)

**Comment by mj426382** [comment]
`useContractCall` is deprecated, try to use `useCall` instead.
