### ISSUE TITLE
[feature] can we add the original error code to the useContractCall state error?

### ISSUE THREAD

**Issue by finalquest** [TrueFiEng/useDApp#365]
Hi. I been using useDapp en the last couple of days. Awesome lib. 

But I encountered some issues trying to handle the errors on the useContractCalls. 
The state only has the errorMessage, that currentyly maps to the errorMessage that metamask is throwing. 

Can we add the errorCode that metamask throw as well?. 
Or the original error as another property in the state object? 

I would gladly submit a pr with this changes. 

Regards

**Comment by darrenrogan** [comment]
+1

**Comment by tt-marek** [comment]
Sorry for slow response! We were crunching on a few topics last months.

errorCode should be there, I would be happy to review such a PR.

**Comment by mj426382** [comment]
This opportunity with multicall2 is avaialble now, it was impossible with multicall1.
Also useContractCall is deprecated, please use useCall now.
