### ISSUE TITLE
 useEthers() not works on ftm test net

### ISSUE THREAD

**Issue by AlbertWh1te** [TrueFiEng/useDApp#370]
I am using usdDapp on ftm test net,it useEthers not works.
But it works perfect on ETH mainnet ,ETH test net and FTM main net.
```JavsSript    
const {activateBrowserWallet, account, chainId, active, activate, deactivate} = useEthers()
```

**Comment by tt-marek** [comment]
It seems only multicall address is missing to close #366

**Comment by mj426382** [comment]
As we have Fantom testnet support i close tthis.
