### ISSUE TITLE
Invalid contract call when using useContractCall

### ISSUE THREAD

**Issue by vellit** [TrueFiEng/useDApp#371]
Using the code: 
`  const [paused] = useContractCall({
    abi: contractInterface,
    address: contractAddress,
    method: "paused",
    args: [],
  }) ?? [];`
Causes the error: `Invalid contract call: address=0xCEb299e0f8B6fA3Ef5D698a318806b950275D0eF method=paused`
Contract is deployed on Rinkeby. Abi provided contains required method.
What am i doing wrong?

**Comment by threepwave** [comment]
I'm getting a similar issue when trying to call a contract on my localhost (hardhat). useContractFunction works great, but useContractCall is throwing an error no matter what method name I pass in (in this case a getter called `mintPrice`).

The specific error I'm getting are:
Client-side: `failed to check transaction hash: undefined Error: invalid hash (argument="value", value=undefined, code=INVALID_ARGUMENT, version=providers/5.4.1)` in
Hardhat-side: 
`code: -32603 message: "Error: Transaction reverted: function selector was not recognized and there's no fallback function"`
`eth_call
  Contract call:       MyContract#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xa4899d35897033b927acfcf422bc745916139776

  Error: Transaction reverted: function selector was not recognized and there's no fallback function`


```
import Image from 'next/image'
import styles from './Mint.module.css'
import { useContractFunction, useContractCall, useEthers } from '@usedapp/core'
import { utils, providers } from 'ethers';
import { Contract } from '@ethersproject/contracts'
import abi from '../../data/test.abi'

export default function Mint(){
    if(typeof window === 'undefined') {
         // Don't call these functions serverside to prevent 'window = undefined' errors
        return(     <div className={styles.twocolumn}>
         <h2 className={styles.price}>Price 0.35ETH  <button className={styles.mintButton} onClick={() => {mint('0.1')}}>Mint</button></h2>
         <p className={styles.description}>
             Price will increase after each mint. Please wait for your transaction to complete before minting the next map.
         </p>
      </div>)  
    }

    const { account } = useEthers()
    const cncInterface = new utils.Interface(abi)
    const cncContractAddress = '0xA4899D35897033b927acFCf422bc745916139776'

    const provider = new providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner(account)
    const contract = new Contract(cncContractAddress, cncInterface, signer)

    // Get mint price
    const [price] = useContractCall({
        abi: cncInterface, 
        address: cncContractAddress, 
        method: 'mintPrice', 
        args: []
    }) ?? [];
    console.log(`price: ${price}`)
    
    
    // Setup mint function
    const { state, send } = useContractFunction(contract, 'mint', { transactionName: 'Mint' });
    
    const mint = (amount) => {
        send({value: utils.parseEther(amount)});    
    } 
    

   return(
       <div className={styles.twocolumn}>
           <h2 className={styles.price}>Price 0.35ETH  <button className={styles.mintButton} onClick={() => {mint('0.1')}}>Mint</button></h2>
           <p className={styles.description}>
               Price will increase after each mint. Please wait for your transaction to complete before minting the next map.
           </p>
        </div>
   )
}
```

**Comment by ccarnino** [comment]
Same issue here

**Comment by youngjuning** [comment]
Same issue here

**Comment by youngbloodk** [comment]
Same issue

**Comment by mj426382** [comment]
UseContractCall is deprecated, please use useCall now:)
