### ISSUE TITLE
Stronger types for `useContractCall` using TypeChain

### ISSUE THREAD

**Issue by hasparus** [TrueFiEng/useDApp#375]
Howdy 👋

Me and @krzkaczor started thinking recently about possible stronger types for `useContractCalls` and `useContractCall` based on types generated by [TypeChain](https://github.com/dethcrypto/typechain).

Is stronger typing for calls something you would consider merging to `useDapp`? Is this something the users would be interested in?

For example, with the following change to `useContractCalls` signature, we could infer required types from `ethers` contract instance.

<figure>

```ts
import { Dai, Dai__factory } from "./src/typechain"; // generated by TypeChains ethers-v5 target

const daiInstance = Dai__factory.connect(address, signer) // creates instance of ethers.Contract

const [balance] = useContractCalls(daiInstance, [{
  // daiInstance has `.address` and `.interface` properties so we wouldn't need to pass `address` and `abi` here
  method: "balanceOf", // method names and can be derived from contract's instance `.functions` dictionary
  args: [""0x2e465ddca6d2c6c81ce6f260ab13148d43e93371"]
}]);
```

<figcaption><i><small>(users could leverage <a href="https://github.com/dethcrypto/eth-sdk">eth-sdk</a> for automatic ABI management and creation of that ethers contract instance)</small></i></figcaption>

</figure>

<p></p>

I made a [repo with some more possible APIs](https://github.com/hasparus/typechain-usedapp/blob/main/README.md) including typelevel implementation.

Frankly speaking, we'd prefer to collaborate on a solution in `useDapp` without need for codegen, because it would spare us the maintenance of another TypeChain target 😅

**Comment by noobshow** [comment]
@marekkirejczyk @nezouse  This looks good and can be a second function for existing functions that want to enjoy the whole reason using Typescript in the first place...

Seeing the linked repo, it is a prototype with multiple experiences, ideas and functions to choose from that could go directly into useDapp or maybe as a plugin...

Can something be worked on together to give useDapp a better typing experience?

Great work there @hasparus  && @krzkaczor.

**Comment by tt-marek** [comment]
Added to roadmap, we have working prototype in the company (based on yours), hope to release as experimental support soon. No clear date thou.

**Comment by mj426382** [comment]
Added typechain with useCall hook.
