### ISSUE TITLE
useEtherBalance returns undefined

### ISSUE THREAD

**Issue by Vanclief** [TrueFiEng/useDApp#387]
Following the basic example:

```
export function App() {
  const { activateBrowserWallet, deactivate, account } = useEthers()
  const userBalance = useEtherBalance(account)


  return (
    <div>
      {!account && <button onClick={activateBrowserWallet}> Connect </button>}
      {account && <button onClick={deactivate}> Disconnect </button>}

      {account && <p>Account: {account}</p>}
      {userBalance && <p>Ether balance: {formatEther(userBalance)} ETH </p>}
    </div>
  )
}
```

I can get my account address, but I get undefined for `userBalance`, no matter what I do it is always undefined.

**Comment by ccarnino** [comment]
Same here on localhost. It used to work.

**Comment by Vanclief** [comment]
@hasparus Could you please take a look at his?

**Comment by hasparus** [comment]
Hey @Vanclief, I have literally one commit here, and it only affects the docs. I'm not the best person to ask about this :D

**Comment by Vanclief** [comment]
My bad! Just saw who was the latest contributor...

**Comment by Vanclief** [comment]
@nezouse @Szymx95 are you the main contributors for this project?

**Comment by nezouse** [comment]
Hi @Vanclief , could you provide some reproduction? I created a small sample, but it's working for me so hard to guess what could go wrong with it.

https://replit.com/@nezouse/SevereBlushingRange#src/App.tsx

**Comment by Szymx95** [comment]
Hi @Vanclief did you wrap your App in a provider like in example ?

```
const config = {
  readOnlyChainId: ChainId.Mainnet,
  readOnlyUrls: {
    [ChainId.Mainnet]: 'https://mainnet.infura.io/v3/62687d1a985d4508b2b7a24827551934',
  },
}

ReactDOM.render(
  <DAppProvider config={config}>
    <App />
  </DAppProvider>,
  document.getElementById('root')
)
```

**Comment by Vanclief** [comment]
Hello @nezouse  and @Szymx95, thanks for the response. We did wrap the

**Comment by Vanclief** [comment]
Hello @nezouse, @Szymx95 thanks for the quick reply. So this is our code:

App.tsx
```
const config = {
  readOnlyChainId: ChainId.Mainnet,
  readOnlyUrls: {
    [ChainId.Mainnet]: 'https://mainnet.infura.io/v3/xxx',
    [ChainId.Ropsten]: 'https://eth-ropsten.alchemyapi.io/v2/xxx-',
  },
};

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  useEffect(() => {
    const handleRouteChange = (url: any) => {
      ga.pageview(url);
    };
    router.events.on('routeChangeComplete', handleRouteChange);
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);

  return (
    <DAppProvider config={config}>
      <Component {...pageProps} />
    </DAppProvider>
  );
}
```

TransparentButton.tsx
```
export const TransparentButton = ({ text }: { text: ReactNode }) => {
  const { account, activateBrowserWallet } = useEthers();
  const etherBalance = useEtherBalance(account);

  useEffect(() => {
    console.log('Account', account);
    console.log('EtherBalance', etherBalance);
  }, [account, etherBalance]);

  return (
    <div className={styles.container} onClick={account ? undefined : () => activateBrowserWallet()}>
      {account ? <div className={styles.text_container}>{formatAddress(account)}</div> : <div className={styles.text_container}>{text}</div>}
    </div>
  );
};
```

That is printing:
![Screenshot_20211119_090349](https://user-images.githubusercontent.com/13844339/142644361-38ed463b-a2c7-44bd-95e1-c45afbf41dda.png)

Seems the error is on `Invalid contract call: address= method= args=`. I checked out the snippet nezouse shared and works fine, so I am not sure of why it keeps returning the Eth balance as undefined. Could it be related to trying this on Ropsten?

**Comment by Vanclief** [comment]
Error trace:

![Screenshot_20211119_091804](https://user-images.githubusercontent.com/13844339/142646517-52435943-df9c-4af8-b24e-7ace0ca9878f.png)

**Comment by PaulRuigrok** [comment]
any update on this?

**Comment by jiyosub** [comment]
Same issue.  Account isn't initialised yet before the call to useEtherBalance.  But it looks like it should be able to gracefully accept a falsy value.

**Comment by Vanclief** [comment]
@ccarnino @PaulRuigrok @jiyosub 

I gave up on this library and ended up using wagmi which was excellent.  

Github: https://github.com/tmm/wagmi
Dos: https://wagmi-xyz.vercel.app/

**Comment by ccarnino** [comment]
I checked wagmi lately. And the documentation is top notch. I will decide soon if give it a try

**Comment by wanaii** [comment]
Is anyone still here following this issue? I still got this problem even if had every package updated: 

"react": "^18.1.0",
"@usedapp/core": "^1.0.2",
"ethers": "^5.6.5",
"resolutions": {
    "@ethersproject/abi": "5.6.1",
    "@ethersproject/contracts": "5.6.0"
  },

It's just an overnight rebuild then the useEtherBalance failed, before I upgraded everything related.

**Comment by wanaii** [comment]
I'd use wagmi as suggested for tempo use, but definitely would love some one have useDapp checked! Thx in advance for any help.

**Comment by BrunoEleodoro** [comment]
here's what I did to fix this issue:

```
<DAppProvider
      config={{
        networks: [Avalanche, Localhost, Hardhat],
        readOnlyChainId: ChainId.Hardhat,
        readOnlyUrls: {
          [ChainId.Avalanche]: 'https://api.avax.network/ext/bc/C/rpc',
          [ChainId.Localhost]: 'http://localhost:8545',
          [ChainId.Hardhat]: 'http://localhost:8545',
        },
        multicallAddresses: {
          [ChainId.Localhost]: '0x0FB54156B496b5a040b51A71817aED9e2927912E',
          [ChainId.Hardhat]: '0x0FB54156B496b5a040b51A71817aED9e2927912E',
        },
      }}
    >
```
