### ISSUE TITLE
connector.off isn’t a function

### ISSUE THREAD

**Issue by brothanek** [TrueFiEng/useDApp#395]
After using activate() or activateBrowserWallet() and then deactivate() - after this even activate() triggers this error

This error occurs

![image](https://user-images.githubusercontent.com/61789527/142260938-d3b0c977-efd4-42fb-a808-016b85e3f7c1.png)

I would really appreciate some help 🙏

**Comment by mj426382** [comment]
In the newest useDapp release using web3-react connectors is deprecated and may lead to unexpected behavior.
https://usedapp-docs.netlify.app/docs/Guides/Migration/to-1.0.0

I'd suggest to use specified wallet provider like here:
https://usedapp-docs.netlify.app/docs/guides/connecting/wallet%20connect/
