### ISSUE TITLE
Use StaticJsonRpcProvider or InfuraProvider to avoid eth_ChainId calls. 

### ISSUE THREAD

**Issue by jhirn** [TrueFiEng/useDApp#397]
Hello again. 

With my site having just gone live, I'm noticing a ton of ethChianId calls in Infura. According to https://github.com/ethers-io/ethers.js/issues/901, a solution would be to use `ethers.providers.InfuraProvider` and not the `ethers.providers.JsonRpcProvider`. I understand there is also a StaticJsonRpcProvider as well. 

Unfortunately I'm not 100% sure how to go about this and what side-effects, if any, I may face by doing so. Opening an issue to get some conversation around how to do this or why it might not be as simple as it seems. 

Thank you!

**Comment by mj426382** [comment]
In the newest useDapp version, we use StaticJsonRpcProvider instead of not static one and you can also pass your provider that reads the chain state.
