### ISSUE TITLE
Allow to add custom networks with any ChainId

### ISSUE THREAD

**Issue by tt-marek** [TrueFiEng/useDApp#408]
Continuation of #47
Related to #132

Currently it is impossible to use a new network without adding PR to useDApp.
We would like to change it by adding list of all possible networks to config, that can be modified.
To do so I propose to:

### Add new variable to `Config` - `networks`, i.e.

```ts
export const DEFAULT_CONFIG: FullConfig = {
  ...
  supportedChains: DEFAULT_SUPPORTED_CHAINS.map((network) => network.chainId),
  networks: DEFAULT_SUPPORTED_CHAINS
```  
so that

- `supportedChains` are list of chains ids that useDApp will connect without throwing error
- `networks` are Chain[] storing list of all known Chain and their configurations

User can dynamically edit config by using:

```ts
const config = useConfig()
const updateConfig = useUpdateConfig()
updateConfig({ networks: [...config, {...}])
```

Could be further develop into something with nicer syntax, i.e.
```ts
const {config, addNetwork, removeNetwork, ...} = useConfigReducer()
addNetwork({...})
```

### Replace all usages of constants to use useConfig, i.e.

`DEFAULT_SUPPORTED_CHAINS` -> `const {networks} = useConfig()`

Replace all usage in functions like:
```ts
getChainById(chainId: ChainId)
getExplorerAddressLink(address: string, chainId: ChainId)
getExplorerTransactionLink(transactionHash: string, chainId: ChainId)
getChainName(chainId: ChainId)
isTestChain(chainId: ChainId)
isLocalChain(chainId: ChainId)
etc...
```

### Change `ChainId` type, i.e.
```
export type ChainId = KnownChainId | number
export enum KnownChainId {
  ...
}
```

or simply to `number`

### Add documentation

Last but not least we would like to have a guide on how to add support for a new network:

- to your project
- issue a PR

### Notes

This will be breaking change and will require to advance version accordingly.

**Comment by tt-marek** [comment]
Looking for comments @Szymx95 @nezouse @sz-piotr @gasolin 

@gasolin Would you like to implement?

**Comment by tarrencev** [comment]
Hey! Thanks for the great work on useDapp. Just wanted to chime in and suggest using CAIP identifiers: https://github.com/ChainAgnostic/CAIPs. Thats the standard with the most traction at this point. Used by wallet connect, metamask, ect.

**Comment by gasolin** [comment]
> ### Add new variable to `Config` - `networks`, i.e.
> ```ts
> export const DEFAULT_CONFIG: FullConfig = {
>   ...
>   supportedChains: DEFAULT_SUPPORTED_CHAINS.map((network) => network.chainId),
>   networks: DEFAULT_SUPPORTED_CHAINS
> ```

@tt-marek if not need the backward compatibility of DAppProvider, maybe we can use single `networks` or `chains` Config prop to pass in support networks configs, generate the `supportedChains` Id lists, and `multicallAddresses` (which is chain related, not make much sense to pass as a DAppProvider Confifg prop for the multi-chain case)

so I suggest to 

1. add a new `networks` or `chains` prop in Config to accept any Configs define in packages/core/src/model/chain (or outside Config when ready)
2. deprecated `supportedChains`, `multicallAddresses` props in Config

**Comment by gasolin** [comment]
BTW is dynamically editing networks in config a common use case? Is there some actual usage scenario?

**Comment by tt-marek** [comment]
@tarrencev Would you elaborate how would you use CAIP identifiers in useDApp?

**Comment by tarrencev** [comment]
> @tarrencev Would you elaborate how would you use CAIP identifiers in useDApp?

my suggestion would just be to use them rather than plain chain id numbers. for now, useDApp only supports evm chains so it is a bit redundant, but will allow for it to be more interoperable with future multi chain tooling. for example, once non-evm eth rollups start landing, i.e. starknet, i assume uses will eventually want useDApp support them.

**Comment by tt-marek** [comment]
@gasolin Good points

I agree that dynamically editing networks indeed is not a strong use case 
My thinking was that we use it on application load to set up networks - it does feel unnecessary complex

So if I am getting right your idea, configuration would be something like this:
```ts
const config: Config = {
    networks: [Mainnet]
    readOnlyUrls: {
      [Mainnet.chainId]: 'https://mainnet.infura.io/v3/62687d1a985d4508b2b7a24827551934',
    },
  }
```
Correct?

**Comment by sz-piotr** [comment]
The type `enum | number` means that chain ids outside the built-in range feel like a second class citizen. Instead I propose to use nominal typing as described here: https://basarat.gitbook.io/typescript/main-1/nominaltyping#using-interfaces. As referenced by the linked article the approach was also used internally in the typescript compiler.

The idea is to create an "impossible" type:
```ts
interface ChainId extends Number {
    _chainIdBrand: number
}
```

Then have a "constructor" of the same name that casts numbers to this type:
```ts
function ChainId (value: number) {
    if (!Number.isInteger(value) || value < 0) {
        throw new TypeError('ChainId must be a non-negative integer')
    }
    // we cast to unknown first as a direct number -> ChainId cast results in an error
    return value as unknown as ChainId
}
```

Creating the basic chainId constants is now very simple and is the same for in-house and third-party code:
```ts
const MAINNET_CHAIN_ID = ChainId(1)
const ROPSTEN_CHAIN_ID = ChainId(42)
```

Having this new type means that we gain huge type safety benefits with clear error messages:
```ts
// Type 'ChainId' is not assignable to type 'number'. (2322)
const myNumber: number = ChainId(1)
// Type 'number' is not assignable to type 'ChainId'. (2322)
const myChainId: ChainId = 1
// Operator '+' cannot be applied to types 'ChainId' and 'ChainId'. (2365)
const sum = ChainId(1) + ChainId(2)
```

The only downside is that in internal code where numbers are actually required a simple cast is needed
```ts
const chainId = ChainId(1)
const justANumber: number = +chainId
```

**Comment by vm06007** [comment]
what is left for this to happen? I'm still not able to provide custom chain as there's this check `if (isChainId(chainId)) {`
<img width="726" alt="Screen Shot 2021-12-08 at 1 51 17 AM" src="https://user-images.githubusercontent.com/1138692/145088808-84431deb-fa4e-448a-bf59-0f10fcdd001a.png">

any way to use smartBCH (chainId 10000) without making a PR?

**Comment by vm06007** [comment]
any chance to check this @tt-marek ?

**Comment by gasolin** [comment]
@sz-piotr @tt-marek I feel declaring `chainId` as `number` (vs. Enum or custom ChainId type) is good enough. Most of dev will import Chain from @usedapp/core, the other dev who needs custom network will refer the code in @usedapp/core, and its easy to realize the whole thing failed if he didn't use number for chainId

**Comment by tt-marek** [comment]
@gasolin Quick summary of my thinking below.

Pros for using Nominal Typing:
- type-safety (as described by @sz-piotr) 
- implementation is just few lines
- It will be easy to add number as an option in the future, while restricting from number

Pros for using `number`:
- even simpler implementation
- less documentation required
- no compatibility  breaking changes

All and all I think number is fine for now. I would still love to try nominal typing in the future.

**Comment by RongxinZhang** [comment]
@tt-marek Just wanted to see if there's any updates on what your decisions has been.

**Comment by tt-marek** [comment]
@RongxinZhang 
We are now focusing on new hook (useCall - with types and error handling) and multi chain support.
We will go back to configuration after that.

**Comment by rzadp** [comment]
It's possible now, please review our [guide](https://usedapp-docs.netlify.app/docs/Guides/Connecting/Custom%20Chains) on this topic.

**Comment by vm06007** [comment]
> @RongxinZhang We are now focusing on new hook (useCall - with types and error handling) and multi chain support. We will go back to configuration after that.

can `useCall` be used with chainId? so can specify on which chain the call should happen?

**Comment by vm06007** [comment]
```
    const { value, error } = useCall(tokenAddress && {
        contract: new Contract(
            tokenAddress,
            ERC20Interface
        ),
        method: "totalSupply",
        args: [],
    }, {chainId: 10000}) ?? {}

    if (error) {
        console.error(error.message);
        return undefined;
    }

    return value?.[0];

```

is this correct?

**Comment by rzadp** [comment]
@vm06007 Yes, that looks correct.
Keep in mind you have to have the corresponding chain configured in `readOnlyChainUrls` of your useDApp config.

**Comment by nghia45** [comment]
> what is left for this to happen? I'm still not able to provide custom chain as there's this check `if (isChainId(chainId)) {` <img alt="Screen Shot 2021-12-08 at 1 51 17 AM" width="726" src="https://user-images.githubusercontent.com/1138692/145088808-84431deb-fa4e-448a-bf59-0f10fcdd001a.png">
> 
> any way to use smartBCH (chainId 10000) without making a PR?

May I know how did you resolved this? I was stuck at the same place
