### ISSUE TITLE
Example of app without exposing API endpoint with readOnlyUrls

### ISSUE THREAD

**Issue by kamsec** [TrueFiEng/useDApp#413]
Hey,
in example app you show the following snippet:
```python 
const config = {
  readOnlyChainId: ChainId.Mainnet,
  readOnlyUrls: {
    [ChainId.Mainnet]: 'https://mainnet.infura.io/v3/62687d1a985d4508b2b7a24827551934',
  },
}

ReactDOM.render(
  <DAppProvider config={config}>
    <App />
  </DAppProvider>,
  document.getElementById('root')
)
```
but if we do it like that, the API key will be exposed for everyone in developer tools.
It should be done with separate backend which stores API key and communicates with infura endpoint on behalf someone using frontend app.

Minimal working example of such backend+frontend application would helpful.

**Comment by outdoteth** [comment]
This is just the current status quo in web3. Even projects like uniswap, compound etc. expose the infura key in the frontend.

**Comment by jhirn** [comment]
I have a personal infura key for local/test and a different one for prod which is whitelisted in Infura to only accept connections from my app's domain. I serve my js via a Rails app and read the links from a data attribute on head but you use dotenv or something else for a production build.

**Comment by rzadp** [comment]
> the API key will be exposed for everyone in developer tools

True.

> This is just the current status quo in web3

Also true.

> Minimal working example of such backend+frontend application would helpful.

I consider this out of the scope of useDApp - for DApps as in web apps without a dedicated backend, just the blockchain.
We want to provide a relatively easy entry to blockchain, where all you need is a web app - but that unfortunately has problems with all the "secrets" in the code available to everyone.

> which is whitelisted in Infura to only accept connections from my app's domain

This is the way to go, so I will close the issue emphasising this as the solution.
So - for production, your Infura/Alchemy/other provider "secret" is exposed, but you configure it in your provider to only accept connection from your domain.
And, if possible, you could configure it to only accept queries to your contracts on the blockchain, none other.
