### ISSUE TITLE
Changing a users network to the supported network

### ISSUE THREAD

**Issue by dobbobalina2** [TrueFiEng/useDApp#416]
I can't quite figure out how to change the user network to the supported network as it appears using this library I can't access `window.ethereum`.

change meaning add the required network to use my website to their metamask. Any help would be appreciated thanks!

Is there a recommended way to do this ?

**Comment by noisetheory** [comment]
interested in this as well.

id like to prompt to switch metamask network if the user is on the wrong chain.

**Comment by dobbobalina2** [comment]
After looking into it some more, with metamask at least there needs to be a request sent  to the RPC. In Ethers this would be `provider.request,` however it appears the provider given  from the hook `useEthers()`  doesn't have such a property. Not sure if its because you guys are using an old library of ethers or if you guys just abstracted  it away

**Comment by jhirn** [comment]
> Not sure if its because you guys are using an old library of ethers or if you guys just abstracted it away

It's using the provider from web3-react. But hopefully that dependency is soon to change.

**Comment by dobbobalina2** [comment]
I solved the issue. This is how you would do it.


` useEffect(() => {
    if(active == true ) {

      if (chainId != 80001) {
        library.provider.request({
          method: 'wallet_addEthereumChain',
          params: [
            {
              chainId: '0x13881',
              chainName: 'Mumbai testnet',
              nativeCurrency: {
                name: 'matic',
                symbol: 'matic',
                decimals: 18,
              },
              rpcUrls: [
                ' https://polygon-rpc.com ',
                'https://rpc-mainnet.matic.network',
                'https://rpc-mainnet.maticvigil.com',
              ],
              blockExplorerUrls: ['https://polygonscan.com/'],
            },
          ],
        })
      }
    } 
  }, [active ])`

**Comment by RongxinZhang** [comment]
Thank you @dobbobalina2 were you able to get it work in Typescript?

**Comment by RongxinZhang** [comment]
@dobbobalina2 @jhirn  Thank you for the info. However, I'm now getting  the following error:
```sh
network-connector.esm.js:53 Uncaught (in promise) RequestError: Method wallet_addEthereumChain not supported.
    at network-connector.esm.js:153:1
```

**Comment by jhirn** [comment]
0.6.3 was the version when this worked for me. Haven't updated the site lately as it was finished.
