### ISSUE TITLE
useContractFunction(...) state does not update after rejected transaction

### ISSUE THREAD

**Issue by 0xCryptodd** [TrueFiEng/useDApp#418]
Hello all,

1st off: thank you for developing useDapp, super useful 🙏

I ran into an issue, where if a user rejects a transaction, and then recalls "send", the "state" is not updated, but remains as rejected.

Here's my code (in js):

The hook:
```
export function useTokenApproval(tokenAddress) {
    const tokenContract = new Contract(tokenAddress, Erc20Abi);
    const {state, send, events} = useContractFunction(tokenContract, 'approve', {});
    return {state, send, events};
}
```
The React component:
```
export function ApproveButton({tokenAddress, spenderAddress, amount}) {
    const { state, send, events } = useTokenApproval(tokenAddress);
    
    function handleApprove() {
        send(spenderAddress, amount);
        setModalVisible(true); // modal shows state.status
    }
    etc.
}
```

This is what's happening:
- user calls handleApprove();
- user gets metamask popup to approve transaction
- user rejects transaction in metamask
- user clicks on handleApprove() again, and gets metamask popup to approve transaction (another one)
- at this stage, the state is still the state of the 1st rejected transaction, instead of the second new one

I was wondering whether this is normal, as in, why is state not updated between a user rejecting a transaction and then initiating another one?

Thank you for your help. Let me know if I can provide more details that would be helpful in solving this issue.

**Comment by 0xCryptodd** [comment]
Any solutions for this?

**Comment by owahlen** [comment]
I found a workaround digging into the [send method](https://github.com/EthWorks/useDApp/blob/e5f095101c9f35439a0fb74b3bec0e000c3502b2/packages/core/src/hooks/useContractFunction.ts#L33): It returns a promise that [resolves](https://github.com/EthWorks/useDApp/blob/e5f095101c9f35439a0fb74b3bec0e000c3502b2/packages/core/src/hooks/usePromiseTransaction.ts#L21) if there is a `TransactionResponse` or an exception. A user rejecting a transaction in Metamask leads to such an exception.
Thus in your example you could await this promise and then setModalVisible(true):
```
function handleApprove() {
    (async () => {
        // wait for Metamask to close and TransactionResponse
        await send(spenderAddress, amount);
        setModalVisible(true); // modal shows state.status
    })();
}
```

**Comment by 0xCryptodd** [comment]
> I found a workaround digging into the [send method](https://github.com/EthWorks/useDApp/blob/e5f095101c9f35439a0fb74b3bec0e000c3502b2/packages/core/src/hooks/useContractFunction.ts#L33): It returns a promise that [resolves](https://github.com/EthWorks/useDApp/blob/e5f095101c9f35439a0fb74b3bec0e000c3502b2/packages/core/src/hooks/usePromiseTransaction.ts#L21) if there is a `TransactionResponse` or an exception. A user rejecting a transaction in Metamask leads to such an exception. Thus in your example you could await this promise and then setModalVisible(true):
> 
> ```
> function handleApprove() {
>     (async () => {
>         // wait for Metamask to close and TransactionResponse
>         await send(spenderAddress, amount);
>         setModalVisible(true); // modal shows state.status
>     })();
> }
> ```

Thank you! I will test this out

**Comment by dyst1292** [comment]
I am having exactly the same problem, trying to find a solution.

**Comment by hiddentao** [comment]
Have the same problem myself now.

**Comment by hiddentao** [comment]
Looks like `resetState()` has been added in master -> https://github.com/EthWorks/useDApp/pull/472
