### ISSUE TITLE
useContractCall msg.sender doesn't work

### ISSUE THREAD

**Issue by chichke** [TrueFiEng/useDApp#419]
While you cannot specify a msg.sender with the useContractCall function some of my function like `withdraw` doesn't work.

https://github.com/EthWorks/useDApp/blob/485530a40eeb50b7ed5d7fedce00ff12a5d93a1c/packages/core/src/hooks/useContractCall.ts#L26-L31

I had to change my function from this :

```solidity
    function getBet()
        external
        view
        onlyCurrentACPI
        returns (uint256)
    {
        return _balance[msg.sender][_currentRound];
    }
```

to this: 

```solidity
    function getBet(address account)
        external
        view
        onlyCurrentACPI
        returns (uint256)
    {
        return _balance[account][_currentRound];
    }
```

Looking for help :)

**Comment by hiro00125** [comment]
Hello, everybody!
I have same issue, please help me!

**Comment by mj426382** [comment]
We are going to add connectors to useDapp soon which solve that problem:0

**Comment by hiro00125** [comment]
When can you add it?

**Comment by gsteenkamp89** [comment]
yeah being able to pass in `overrides` object is quite important.

**Comment by rzadp** [comment]
I'm going to close this one and merge it with https://github.com/TrueFiEng/useDApp/issues/897 as it is the same problem.

There might be problems with implementing this feature - https://github.com/TrueFiEng/useDApp/issues/897#issuecomment-1193888691
