### ISSUE TITLE
useEthers() has a short time delay

### ISSUE THREAD

**Issue by hirokimoto** [TrueFiEng/useDApp#424]
When I try to get account information from useEthers, it does have a short time deplay.

In more detail, as soon as I refresh the web page, the account information from useEthers is undefined. After about 0.5 second, it returns the correct account information.

This makes unexpected behavior on React app, so I strongly feel that we should figure out this issue to use something like async/await.

**Comment by noobshow** [comment]
That's the recommended way to go, those informations aren't always available onLoad, I would advise you check the example source code on how to proceed by either checking if it is undefined or not before you output a page.

Just like it will be undefined if a wallet is not connected.
I hope that helps?

**Comment by mj426382** [comment]
Try using `isLoading` from useEthers.

**Comment by mingxin-yang** [comment]
> Try using `isLoading` from useEthers.

I tried to use `isLoading`, but if there is an account at the moment, `isLoading` will change according to f`alse`, `true`, `false`, and when there is no account, `isLoading` will only have a `false` state, which will cause many problems.

@mj426382

**Comment by rzadp** [comment]
> That's the recommended way to go, those informations aren't always available onLoad, I would advise you check the example source code on how to proceed by either checking if it is undefined or not before you output a page.

That's the correct approach.

@mingxin-yang So it is expected of `useEthers` to load all data with some delay, and it's expected of a React app to change/update shortly after refresh.

Or can you describe your situation if this is not a feasible thing?

**Comment by mingxin-yang** [comment]
@rzadp Hi, I ended up solving the problem using a method that determines if there is a local token saved after I logged in, relying solely on state would make the project load between pages.
