### ISSUE TITLE
UnsupportedChainIdError

### ISSUE THREAD

**Issue by jacobedawson** [TrueFiEng/useDApp#434]
In web3-react, we are able to catch errors during activation or network change, and check the type of the error, for example:

```
import { UnsupportedChainIdError } from '@web3-react/core'
// ...

function Component () {
  const { error } = useWeb3React()
  const isUnsupportedChainIdError = error instanceof UnsupportedChainIdError
  // ...
}
```

It's not clear from the documentation as to how we can achieve the same thing. Is it possible to do this in useDapp?

**Comment by ducndt** [comment]
Hi @jacobedawson , your example is catch error in UnsupportedChainIdError. I don't think why my app only can not catch this error. Do you have more example?
