### ISSUE TITLE
Everytime I log in a new contract is deployed

### ISSUE THREAD

**Issue by sargtier1** [TrueFiEng/useDApp#440]
I have a small app up and running and I wanted to add usedapp to it. I'm not sure why it keeps deploying new contracts every time I visit the page,  has anyone else experienced this?

**Comment by thestrabusiness** [comment]
Howdy, I'm not totally clear on how some of this works, but I think what's being deployed is a multicall contract that's used to aggregate queries more efficiently. What you can do to prevent that from happening is by configuring you `DAppProvider` like so:

```typescript
  <React.StrictMode>
    <DAppProvider
      config={{
        multicallAddresses: {
          "31337": "address where that contract is being deployed here",
        },
      }}
    >
      <App />
    </DAppProvider>
  </React.StrictMode>,
```
The ChainID and address will change depending on your set up. [Check out the docs](https://usedapp.readthedocs.io/en/latest/core.html#config) for more details about the configuration.

**Comment by ianchildress** [comment]
Thank you @thestrabusiness I had been trying to figure this out all day. I'm using ganache and my DAppProvider ended up looking like this:
```
<DAppProvider
    config={{
        multicallAddresses: {
            "1337": "0x6602338AA55E2F65d9DB5644A17AeBD1AA1CdE00",
        },
    }}
>
    <App/>
</DAppProvider>

```
I looked at the ganache transactions and grabbed the address where the contract was deployed.

**Comment by kesar** [comment]
same issue here

**Comment by sargtier1** [comment]
Hey sorry I didn't come back to this, I just rolled everything on my end, but I plan on coming back to implement these suggestions when I checkout useDapp again. I really want to use it!
