### ISSUE TITLE
Is it possible to, or is there documentation on how to get the context and forward it?

### ISSUE THREAD

**Issue by oveddan** [TrueFiEng/useDApp#453]
I'm using react-three fiber, and for this library, you [cannot use external context within its canvas renderer](https://docs.pmnd.rs/react-three-fiber/advanced/gotchas#consuming-context-from-a-foreign-provider)

However, there is a way around this, by [manually passing the context through](https://docs.pmnd.rs/react-three-fiber/advanced/gotchas#consuming-context-from-a-foreign-provider) to another provider within the canvas element:

```js
function App() {
  const value = useContext(context)
  return (
    <Canvas>
      <context.Provider value={value}>
        {/* children can now read state from context */}
```

I was digging through the useDapp code but cant seem to find a way to grab the contexts that are needed to forward them through.

Is there a way to do something like?

`const dappContext = useContext(DappContext)`

I couldn't find the `DappContex`t type anywhere.

**Comment by mj426382** [comment]
UseDapp exports internal library with whole contexts which are not in the main package.
