### ISSUE TITLE
Adding custom config trouble

### ISSUE THREAD

**Issue by bio-howard** [TrueFiEng/useDApp#456]
Hi, I'm trying to add custom config (which is not present in predefined configs in usedapp).
```
const config = {
  readOnlyChainId: 1666700000,

  readOnlyUrls: {
    [1666700000]: 'https://api.s0.b.hmny.io'
  }
}
```

Unfortunately, if I select the chain in Metamask  it doesn't work. useEthers() iis not reading the account. It works only with other predefined chains like Harmony (mainnet) or Mainnet.

How should the config look like?

**Comment by mj426382** [comment]
Here is tutorial with adding custom chain:)
https://usedapp-docs.netlify.app/docs/Guides/Connecting/Custom%20Chains
