### ISSUE TITLE
How to choose which browser wallet will be activated with `activateBrowserWallet`

### ISSUE THREAD

**Issue by khoanguyen-yang** [TrueFiEng/useDApp#460]
Hi guys,

I currently install Metamask extension and a walllet extension called Coin98 Wallet (https://chrome.google.com/webstore/detail/coin98-wallet/aeachknmefphepccionboohckonoeemg).

When I trigger `activateBrowserWallet`, the Coin98 Wallet will popup. Is there any way that I can activate Metamask instead?

Many thanks.

**Comment by trinzybear** [comment]
Bump, am interested too...

Do we need to resort to `activate`?

**Comment by noobshow** [comment]
You have to use `activate `if your browser have a specific Provider/Connector library, if not i'm not sure how to inform the first InjectedNetwork to not respond

**Comment by mj426382** [comment]
Currently there is only an option to connect to metamask wallet. We are considering to add more wallets soon.
