### ISSUE TITLE
Is there a Discord for useDapp? Would help immensely 

### ISSUE THREAD

**Issue by 0xCryptodd** [TrueFiEng/useDApp#461]
Hi guys,

I find myself having a bunch of questions about useDapp. Not all questions are appropriate for Github issues. 

Is there a Discord where we can ask questions? It would be a great way to receive support from useDapp developers, the community, but also a way to contribute support.

If there is no Discord, can one be created?

Thank you for considering this request.

**Comment by marcin-trust** [comment]
Try https://discord.gg/ppFxC3E44X and #usedapp-support

**Comment by gasolin** [comment]
@marekkirejczyk how about opening the discussion section in github (and disable the wiki)?

**Comment by marekkirejczyk** [comment]
I think about creating a slack channel. The reason is that our company is using slack and it would provide  the biggest chance od someone responding.

**Comment by stoplion** [comment]
Is https://discord.gg/ppFxC3E44X  the official useDapp discord? 

If not, please consider creating a useDapp Discord. Most the GH issues here could be resolved on Discord.

**Comment by niconiahi** [comment]
please create an official discord. People using useDapp could interact with each other

**Comment by rzadp** [comment]
The official useDApp discord is https://discord.gg/ppFxC3E44X
