### ISSUE TITLE
Integrate a way to sign messages

### ISSUE THREAD

**Issue by alexandremartens** [TrueFiEng/useDApp#469]
Is there any way to sign messages with this library?
I couldn't find any information about this.

**Comment by gasolin** [comment]
refer https://docs.ethers.io/v5/api/signer/#Signer-signMessage

might be
```
const { library, chainId } = useEthers()
const signer = library.getSigner()
signer.signMessage("text to sign")
```

**Comment by noobshow** [comment]
Yea, it should be that unless you want to `signTypedDataV4`

> refer https://docs.ethers.io/v5/api/signer/#Signer-signMessage
> 
> might be
> 
> ```
> const { library, chainId } = useEthers()
> const signer = library.getSigner()
> signer.signMessage("text to sign")
> ```

**Comment by mj426382** [comment]
Check example after connecting to wallet:
https://example.usedapp.io/wallet-connect

<img width="1035" alt="Screenshot 2022-06-08 at 11 01 06" src="https://user-images.githubusercontent.com/71319308/172577235-8dceacbc-b13d-451b-adfe-25eae6a23b5a.png">
