### ISSUE TITLE
Invalid queries to an Avalanche RPC endpoint

### ISSUE THREAD

**Issue by Taso69** [TrueFiEng/useDApp#473]
Hi everyone, 

I'm having an issue connecting to Avalanche : I can reproduce this error with the most basic calls (I just want to get the chain ID using a read only access point - not even through a connected wallet).

I'm setting up my config with the following :
```
readOnlyChainId: Avalanche.chainId,
readOnlyUrls: {
    [Avalanche.chainId]: "https://api.avax.network/ext/bc/C/rpc",
}
```
This RPC endpoint is provided by the Avalanche team and is one of the "official" public RPC nodes.

Any call to this RPC endpoint made by useDApp fails with a 415 error : the reason is that the header `"Content-Type: application/json"` is not included in the post request (for example, which has a proper json payload: `'{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}'`), therefore the Avalanche node rejects the call (`invalid content type, only application/json is supported`)

Is there something I'm missing in my configuration ?

**Comment by justincavery** [comment]
I've just encountered this as well.

At the moment we're going through Alchemy eth-mainnet endpoint and it works totally fine. We are testing out using our own infrastructure for this and are also getting the 415 error. 

I can confirm that the default request for the useDApp is using `"Content-Type: text/plain` and we'd like to override that to use `Content-Type: application/json`

**Comment by rzadp** [comment]
Please see: https://github.com/TrueFiEng/useDApp/issues/904#issuecomment-1201300417
