### ISSUE TITLE
Custom network issues

### ISSUE THREAD

**Issue by JCaraballo113** [TrueFiEng/useDApp#482]
So on our project we are using [SKALE](https://skale.network/). Now when trying to add it to my config like so:

```js
const chainId: number = parseInt(process.env.SKALE_CHAIN_ID || '1', 10);

const SkaleChain: Chain = {
    chainId,
    chainName: 'Skale_test',
    isTestChain: false,
    isLocalChain: false,
    multicallAddress: '0xeefba1e63905ef1d7acba5a8513c70307c1ce441', // I actually have no idea what a multicallAddress is but pretty sure SKALE doesn't have one
    getExplorerAddressLink(address: string) {
        return `${process.env.SKALE_EXPLORER}/address/${address}`;
    },
    getExplorerTransactionLink(transactionHash: string) {
        return `${process.env.SKALE_EXPLORER}/tx/${transactionHash}`;
    },
};

const dappConfig: Config = {
    networks: [SkaleChain, Mainnet],
};
```

Once I place a transaction via metamask I get the following error: `TypeError: Unsupported chain`

So I thought, well I need to add the supported chain to my config like so:

```js
const dappConfig: Config = {
    networks: [SkaleChain, Mainnet],
    supportedChains: [ChainId.Mainnet, chainId],
};
```

But if I do that I get: `Cannot read properties of undefined (reading 'chainId')`

Clearly I am doing something wrong and I have no idea what. But the documentation around custom config is really unclear.

**Comment by BeezBeez** [comment]
Same here

**Comment by BeezBeez** [comment]
@JCaraballo113 Have you managed to fix it ?

**Comment by gaspardip** [comment]
As you can see [here](https://github.com/EthWorks/useDApp/blob/master/packages/core/src/providers/config/context.ts#L23), `supportedChains` is deprecated

**Comment by gaspardip** [comment]
It seems [this](https://github.com/EthWorks/useDApp/blob/master/packages/core/src/providers/transactions/reducer.ts#L26) is the issue, this code uses the static enum `ChainId` do determine wether the transaction occurred on a valid network or not, kind of defeating the purpose of the config's `networks` array.

**Comment by noobshow** [comment]
> So on our project we are using [SKALE](https://skale.network/). Now when trying to add it to my config like so:
> 
> ```js
> const chainId: number = parseInt(process.env.SKALE_CHAIN_ID || '1', 10);
> 
> const SkaleChain: Chain = {
>     chainId,
>     chainName: 'Skale_test',
>     isTestChain: false,
>     isLocalChain: false,
>     multicallAddress: '0xeefba1e63905ef1d7acba5a8513c70307c1ce441', // I actually have no idea what a multicallAddress is but pretty sure SKALE doesn't have one
>     getExplorerAddressLink(address: string) {
>         return `${process.env.SKALE_EXPLORER}/address/${address}`;
>     },
>     getExplorerTransactionLink(transactionHash: string) {
>         return `${process.env.SKALE_EXPLORER}/tx/${transactionHash}`;
>     },
> };
> 
> const dappConfig: Config = {
>     networks: [SkaleChain, Mainnet],
> };
> ```
> 
> Once I place a transaction via metamask I get the following error: `TypeError: Unsupported chain`
> 
> So I thought, well I need to add the supported chain to my config like so:
> 
> ```js
> const dappConfig: Config = {
>     networks: [SkaleChain, Mainnet],
>     supportedChains: [ChainId.Mainnet, chainId],
> };
> ```
> 
> But if I do that I get: `Cannot read properties of undefined (reading 'chainId')`
> 
> Clearly I am doing something wrong and I have no idea what. But the documentation around custom config is really unclear.

Is your issue fixed with #543 merge?

**Comment by kunalalite** [comment]
I'm facing same issue for custom chain (KCC testnet in my case). Has anyone found a workaround while using v0.11.0?

**Comment by kunalalite** [comment]
> I'm facing same issue for custom chain (KCC testnet in my case). Has anyone found a workaround while using v0.11.0?

I upgraded from v0.11.0 to v1.0.0 and it is working for me. I will need to change useContractCalls to useCalls due o the upgrade.
