### ISSUE TITLE
How to disable the auto pop-up of the MetaMask panel when visiting the page?

### ISSUE THREAD

**Issue by brioapp** [TrueFiEng/useDApp#505]

**Comment by brunitob** [comment]
same here.

**Comment by brioapp** [comment]
If the user is just browsing the page, we don't need to automatically pop up the panel every time the page is refreshed.

**Comment by noobshow** [comment]
You can disable the `autoConnect` in the config passed to `DappProvider`

```js
const config: Config = {
   ...otherOptions,
   autoConnect: false
}
<DAppProvider config={config}/>

```

**Comment by brioapp** [comment]
Set `autoConnect` to false, so that already connected users cannot connect automatically.

**Comment by vexxvakan** [comment]
This is exactly what I also was just looking for. This improves UX by literally 1000% which is super bullish

**Comment by vexxvakan** [comment]
Has been resolved. Lazy load the component whenever you need it and it works just fine :)
