### ISSUE TITLE
activateBrowserWallet: Expected 0 arguments, but got 2

### ISSUE THREAD

**Issue by stoplion** [TrueFiEng/useDApp#508]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/231343/151908496-de5036be-8ca2-4e3e-a5a6-25f794bfd4eb.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/231343/151908504-92d2265d-6049-40fc-b502-e5171f9be555.png">

activateBrowserWallet call not registering with TS.

**Comment by vanruch** [comment]
Hey @stoplion. Both these args were removed in 0.10 since they weren't really useful and only complicated things. You can just call `activateBrowserWallet()`

**Comment by stoplion** [comment]
Thanks. Was following along w the docs. 
Would be super if docs got updated..
![image](https://user-images.githubusercontent.com/231343/152414375-fd38d6d8-c1a7-4afc-b203-4d21b0d81813.png)

**Comment by stoplion** [comment]
Ok what is the correct way to handle errors? (i.e. I have a Dapp using Avalanche, but I try to connect to Fantom).
When I remove the error function, NO ERROR is thrown. The user is connected to Fantom WITH NO ERROR. 
If the signature of the function has changed, why not update the docs?

**Comment by vanruch** [comment]
You can access errors by reding error field returned by `useEthers`
