### ISSUE TITLE
How to check current connector?

### ISSUE THREAD

**Issue by FanManutd** [TrueFiEng/useDApp#509]
Hi everyone! For example, I use 3 connectors in my dApp: `injectedConnector`(MetaMask), `walletConnectConnector`(WalletConnect) and `bscConnector`(binance). **How can I check which service the user has connected to?** 

I found `connector` property in useEthers hook, but it always return undefined.
![image](https://user-images.githubusercontent.com/90761929/151937589-f88df8f3-26bb-4c98-8e28-e3a33707655f.png)

If there is no such functionality yet, how about adding a property that simply returns the **provider** passed to the `activate` method
![image](https://user-images.githubusercontent.com/90761929/151937841-3c0c27cd-ffdf-4e89-8530-c93f300356e0.png)

**Comment by dmaretskyi** [comment]
Hi @FanManutd , try using `library` property from `useEthers`
