### ISSUE TITLE
Switching networks whilst using a "provider" in version 0.10.0 does not behave as smoothly as switching networks whilst using a "connector"

### ISSUE THREAD

**Issue by JayWelsh** [TrueFiEng/useDApp#510]
In the following examples, I am switching between Rinkeby and Mainnet, the behaviour of switching networks whilst using the "connector" is favourable. It would be ideal if a network switch when using a "provider" resulted in the same behaviour.

Connector network switch (Rinkeby <-> Mainnet):

https://user-images.githubusercontent.com/14224459/151955156-b7a26b2e-97c4-434b-9cdb-acc656fdc57c.mp4

Provider network switch (Rinkeby <-> Mainnet):

https://user-images.githubusercontent.com/14224459/151954749-a9a64711-d886-454d-8f15-89b824a45a99.mp4

It seems that when using the provider (e.g. through web3modal), switching from Rinkeby -> Mainnet throws no error, but also doesn't immediately refresh the on-chain balances/values, as the connector method does. Additionally, when switching from Mainnet to Rinkeby, an error is thrown.

**Comment by mj426382** [comment]
It is caused by lack of rinkeby read-only provider in example app.
It should normally work with this line in config.readOnlyUrls:
[Rinkeby.chainId]: getDefaultProvider('rinkeby').

**Comment by JayWelsh** [comment]
@mj426382 thanks for your response!
