### ISSUE TITLE
can't use existing deployed contract address from truffle on  ganache ui ? 

### ISSUE THREAD

**Issue by Naim-Bijapure** [TrueFiEng/useDApp#528]
as per this raised issue (https://github.com/EthWorks/useDApp/issues/440) 
i replaced contract address inside 
  `    multicallAddresses: {
        // "1337": contractAddress,
        "1337": "0xa5D4496a792Ab98c70f09bE4d3CFABb6fbeD9aA9",
    },`

the issue is when I replace this contract address from useDapp's created contract address no error is there. 

but when I replace this contract address with truffle deployed contract 
then I am getting this error 

`code: -32603
data: {message: 'VM Exception while processing transaction: revert', code: -32000, data: {…}}
message: "Internal JSON-RPC error."
`

I am new to web 3 and wanted to try out this package. 
have explored ethersjs and web3js why useDapp not directly connecting with metamask ?  like ehtersjs .

**Comment by mj426382** [comment]
Did you deploy correct multicall contract?
There are 2 versions:)
