### ISSUE TITLE
How does one recover from activateBrowserWallet error?

### ISSUE THREAD

**Issue by stoplion** [TrueFiEng/useDApp#531]
In the past implementation an error handler was passed to activateBrowserWallet. In the new implementation, no error is passed.

How does one recover from activateBrowserWallet error?

For example..
```
 async function connectWallet() {
    try {
      await activateBrowserWallet();
    } catch (e) {
      alert(JSON.stringify(e));
    }
  }
```

Errors occuring in activateBrowserWallet are not caught, and no alert message is popped up.

(In this example, the error is caused by logging out of Metamask)

**Comment by mj426382** [comment]
With new PR there is only error written in console and useDapp opens new window with metamask extension if it isn't available.
