### ISSUE TITLE
Error Thrown (32002) when auto connected and  logged out of Metamask

### ISSUE THREAD

**Issue by stoplion** [TrueFiEng/useDApp#532]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/231343/153310068-b637db60-476f-41a5-8c27-213c67263897.png">

**Comment by stoplion** [comment]
When logged out of metamask, and upon first load of page this error appear.s

**Comment by stoplion** [comment]
This happens when `autoConnect: true` and `readOnlyUrls` is set (required for autoconnect).
Is there a way to catch this error? Thanks.

**Comment by mj426382** [comment]
Does the issue still persist in the latest version of useDapp?

**Comment by rzadp** [comment]
Does not seem to be an error on recent version of `useDapp`.

Feel free to reopen if there are still problems with a recent version.
