### ISSUE TITLE
inpage.js:1 MetaMask - RPC Error: RetryOnEmptyMiddleware - retries exhausted {code: -32603, message: 'RetryOnEmptyMiddleware - retries exhausted', data: {…}}

### ISSUE THREAD

**Issue by cancan007** [TrueFiEng/useDApp#538]
I'm creating a new dApp with React. Before I uploaded solidity contracts, it workd completly. But after that, some methods of @usedapp/core don't work at all with raising this error on console.
![20220216193624](https://user-images.githubusercontent.com/81799825/154247692-a6dc4876-f851-4be5-b769-8bf42fceeb6e.png)
I confirmed that 'useTokenBalance' and useContractCall don't work at all now. 
I don't know where those issue from.

**Comment by rolandsaven** [comment]
@cancan007 I'd use `multicallVersion: 2` in conifig to obtain the error message

**Comment by cancan007** [comment]
Hi, Roland.
Thank you for giving me an advice.
I want some example what you say.
I added it in config like below image, but nothing changed.

2022年2月20日(日) 19:32 Roland Kalocsaven ***@***.***>:

**Comment by rolandsaven** [comment]
@cancan007 basically you provide a config object with `multicallVersion: 2`

```
export const DAPPCONFIG = {
  readOnlyChainId: Rinkeby.chainId,
  readOnlyUrls: {
    [Rinkeby.chainId]: `https://rinkeby.infura.io/v3/SOMEID`,
  },
  networks: [Polygon, Rinkeby],
  multicallVersion: 2,
};

````

**Comment by cancan007** [comment]
Hi, Roland.
Finally I could solve the problem after adding multicallVersion: 2 in
DAppProvider's config!
I really appreciate your support and advice.
And actually I want to keep communicating with you about programming.
https://github.com/cancan007?tab=repositories
Above URL is my github repos, if you want, please follow me, I would like
to follow back😁

And one more question, I searched about multcallVersion: 2 in google
and @usedapp/core documents, but I couldn't find the explanation anywhere.
Where did you know the parameter?

2022年2月23日(水) 3:48 Roland Kalocsaven ***@***.***>:

**Comment by rolandsaven** [comment]
@cancan007 glad it worked. So multi all v1 does not handle errors properly. 
https://github.com/makerdao/multicall#multicall2-contract-addresses
