### ISSUE TITLE
Multicall results are keyed by contract address might lead to unexpected results

### ISSUE THREAD

**Issue by sirpy** [TrueFiEng/useDApp#545]
Looking at the code here:
https://github.com/EthWorks/useDApp/blob/c29ce02c3741f8acc1e6dff2e8893d6ab40f6e82/packages/core/src/hooks/useRawCalls.ts#L19

The value is fetched keyed by the contract address, this might mean that:
1. it is not possible to query a contract for multiple times?
2. since it is using a reducer, there could be a conflict with some other parallel mutlicall call to the same contract?
A solution would be to key the results by the hash of RawCall data.

Also I think that a nice functionality would be to make multicall use the readonly rpcs and adding the 'chainId' parameter to the RawCall.
Grouping the rawcalls also by chainId, fetching the relevant readonly `library` and querying multicall.
This would allow to query/display values from multiple blockchains and not only the one we are connected to

**Comment by dmaretskyi** [comment]
We did add the ability to specify `chainId` recently. Check out the latest version. You can now query from multiple chains at once: https://usedapp-docs.netlify.app/docs/Guides/Connecting/Multi%20Chain

The calls are stored by: chainId => contractAddress => calldata. This way identical calls are dedeuplicated but you can still have many queries to the same smart contract with different calldata.
