### ISSUE TITLE
How to call useCall function recursively by using usedapp in react  

### ISSUE THREAD

**Issue by apollo0102** [TrueFiEng/useDApp#556]
I  have 2 functions like total(), getvote(voteId) in smart cotract.
How can I implement this code into useEffect?

import { useGetVote, useTotal } from '../../hooks/VotingFactoryContract'
const total = useTotal()
let getVote = useGetVote()
let pollList = [];
for(let i  = 0; i < total; i++){
   pollList.push ( getVote(i));
}

Here are my codes:
----->VotingContract.js
I used useCall function to connect Smart Contract at useTotal(), useGetVote().

**Comment by dmaretskyi** [comment]
You can use `useCalls` to and pass an array of calls.

For example:

```typescript
const results = useCalls(
    tokenList && account
      ? tokenList.map((token: any) => ({
          contract: new Contract(token.address, ERC20Interface),
          method: 'balanceOf',
          args: [account],
        }))
      : []
  )
```

**Comment by apollo0102** [comment]
Hi  Dmytro Maretskyi
Thanks for your help.

**Comment by alexbakers** [comment]
useCalls refreshes the page every 10 seconds, how to prevent this?
the data does not change, but the page is refreshed, why is this happening?
I want it to be updated when the data changes.

**Comment by alexbakers** [comment]
6 updates every 10 sec

<img width="554" alt="image" src="https://user-images.githubusercontent.com/98721968/180665038-f48a7743-d879-4474-b890-32a11d20de4c.png">

**Comment by rzadp** [comment]
@alexbakers useDapp refetches the data on every block. You can make the updates less frequent using a `refresh` configuration in usedapp config - e.g. `refresh: 5` will refresh every 5 block, instead of every 1 block by default.
