### ISSUE TITLE
Unable to authenticate with the provider

### ISSUE THREAD

**Issue by mattxyzeth** [TrueFiEng/useDApp#610]
https://github.com/TrueFiEng/useDApp/blob/8883ba5818e5e591452f16cf6064d366f3ebca12/packages/core/src/constants/type/Config.ts#L4

In order to pass authentication parameters, the provider needs to be able to accept a `ConnectionInfo` object as well as a URL string. This would allow the application to provide either a username and password or authentication headers using a JWT or other auth tokens.

https://docs.ethers.io/v5/api/utils/web/#ConnectionInfo

**Comment by dmaretskyi** [comment]
We could extend the config with the ability to pass in an ethers-compatible provider object. This should allow to specify custom connection options as well.

I'll add a task to the roadmap.

**Comment by dmaretskyi** [comment]
You can now pass ethers provider instances (compatible with `BaseProvider`) to `readOnlyUrls` in config. This should let you configure the `ConnectionInfo`.
