### ISSUE TITLE
ReadonlyNetworksProvider not exported

### ISSUE THREAD

**Issue by mattxyzeth** [TrueFiEng/useDApp#611]
https://github.com/TrueFiEng/useDApp/blob/d04319e5e1126d5dfbfbaa1796e3c172c06b1bb6/packages/core/src/providers/index.ts#L5-L6

Is there a reason why the `ReadonlyNetworksProvider` isn't exported? I'm trying to be more specific with which providers I include in my app. What I want to do is to include all the providers that `DAppProvider` does except `BlockNumberProvider` and `BlockNumbersProvider` since they cause a lot of requests to Infura which could eventually cost money.

**Comment by dmaretskyi** [comment]
We are try to reduce the API surface of the library so some things that are considered an internal implementation detail are not exported. Currently, the querying functionality depends on the block numbers, so it wouldn't work without the provider.

Can you tell me about your use case? Perhaps there's an alternative way to solve it, like only polling the block number on-demand, or disabling it in config altogether.

**Comment by mattxyzeth** [comment]
Hi @dmaretskyi , Thanks for getting back to me. My biggest concern is that if I include the `BlockNumberProvider`, `BlockNumbersProvider`, and the `TransactionProvider` my application starts sending multiple requests per second to my API provider. In this case, it's Infura. I am currently on the free tier since I don't expect to see much traffic for a while. Infura offers 100,000 requests per day on this tier so the amount of requests those providers make is a problem since it will start costing a lot of money very quickly. Do you have a suggestion to avoid this?

**Comment by mattxyzeth** [comment]
That sounds like a good option. For our application I think we need to build something more custom.
