### ISSUE TITLE
`useCall` not working in version 0.12.1

### ISSUE THREAD

**Issue by digitalronin** [TrueFiEng/useDApp#622]
### Problem

Using usedapp/core version 0.12.1, `useCall` does not seem to send any calls to the blockchain network.

### Background

I created a very simple smart contract (SimpleStorage - stores and updates a "message" string), and a react frontend using create-react-app.

The full application source is [here](https://github.com/digitalronin/simple-storage-dapp) if you need it.

`yarn add @usedapp/core` installed version 0.12.1 of usedapp (and version 0.5.6 of ethersproject/contracts)

When I tried to fetch the current message from the contract, `useCall` did not seem to be sending any calls to the network. The value returned from `useCall` was always `undefined`, and when using a local ganache-cli blockchain network, I did not see any `eth_call` log entries after connecting metamask. I saw the same problem when using the Rinkeby network.

This is the react source for my `useGetMessage.ts` hook:

```typescript
import {useCall} from "@usedapp/core"
import {utils} from "ethers"
import {Contract} from "@ethersproject/contracts"
import SimpleStorage from "../contract-data/contracts/SimpleStorage.json"

export const useGetMessage = (contractAddress: string): string => {
  const ssInterface = new utils.Interface(SimpleStorage.abi)
  const ssContract = new Contract(contractAddress, ssInterface)

  const {value: message} = useCall({
    contract: ssContract,
    method: "message",
    args: []
  }) ?? {}

  return String(message)
}
```

After editing my `package.json` file to change the dependencies like this:

```
    "@ethersproject/contracts": "5.5.0",
    "@usedapp/core": "0.11.0",
```

...and then running:

```
yarn add @ethersproject/contracts@5.5.0
yarn add @usedapp/core@0.11.0
```

Then the same application code worked correctly, including the code which invokes `useCall`.

**Comment by ckt22** [comment]
I am also working with version 0.12.1 recently. I believe this version is not stable and has many issues. I will file an issue to cover more details on the problems I encountered later. Perhaps you may try to use an older version first (let say, 0.7.0).

**Comment by dmaretskyi** [comment]
@digitalronin Are you getting any errors in the browser console?

**Comment by digitalronin** [comment]
No errors are logged, afaict. It looks like the useCall executes, but
always returns undefined.

**Comment by gaspardip** [comment]
Seeing the same behavior here.

**Comment by rzadp** [comment]
This should be the same as https://github.com/TrueFiEng/useDApp/issues/644
Please try `0.12.4` version.
