### ISSUE TITLE
Indicate ethers version in docs

### ISSUE THREAD

**Issue by noobshow** [TrueFiEng/useDApp#632]
Its always recommended to indicate ethers(or any core dependencies) version in docs for users to know what versions to upgrade their packages to.

for example, at the Installing section in the documentation for Getting Started
```
yarn add ethers@5.6.2 @usedapp/core
npm install ethers@5.6.2 @usedapp/core
```

**Comment by yivlad** [comment]
Hello,

starting from useDApp v1.0.8 `ethers` is a peer dep, so it's up to you what version of `ethers` to install
