### ISSUE TITLE
Web3Modal in example does not persist

### ISSUE THREAD

**Issue by noobshow** [TrueFiEng/useDApp#643]
https://example.usedapp.io/web3modal
Web3Modal does not persist, even on my project it does not persist after `cacheProvider` is set to `true`

**Comment by noobshow** [comment]
And, i couldn't figure out why it will persist immediately on load, then disconnect right after... I've debugged tons of my codes to figure out why

**Comment by leviyehonatan** [comment]
you mean that it does not auto connect?

**Comment by noobshow** [comment]
That's what was intended whenever cache provider is set to true, and the example was similar to this posted process yet it would auto connect and disconnect immediately

**Comment by noobshow** [comment]
I should close this soon since after i updated to the latest version, its not been an issue again.

**Comment by noobshow** [comment]
Since 0.12.* but I'm currently on the 1.0 version now and no problems, the cacheProvider works well now.

**Comment by charlesAuthentik** [comment]
Hmm I'm also on v1.0 and using the example code from web3modal component. Is there any variation you made to the code to get it work?

**Comment by noobshow** [comment]
You enabled cacheProvider?
Can you wrap the Web3modal instantiation in a useMemo?
Mine seems to disconnect immediately I see it connect onload

**Comment by noobshow** [comment]
I couldn't figure out why or how it started working again, I just found it to be working again after many tries and when I gave up, the only thing I noticed was updating to the latest version at that time, another thing you can try is to clear the localStorage for your website on your browser, especially pertaining to web3modal values.

**Comment by charlesAuthentik** [comment]
Mine only disconnects when refreshes.
Why do we need to wrap it into useMemo?
I checked localStorage and it has no effects.

**Comment by charlesAuthentik** [comment]
Did you end up using the example leviyehonatan mentioned above?

**Comment by noobshow** [comment]
That was similar to what I was using earlier, except for it being in a hook and checking for auto loaded before trying to autoload... So, didn't think there's anything different that would have caused one to work or another.
But mine started working well now.
Are you sure you're having same problem as I did? Showing connected on load, then disconnecting immediately?
