### ISSUE TITLE
0.12.2 broke readonly network contract calls

### ISSUE THREAD

**Issue by chrisirhc** [TrueFiEng/useDApp#644]
I just upgraded to 0.12.2 and it seems that simple useCall/useContractCalls that query from the network are failing.
At first look it seems that the `readOnlyChainId` configuration is not being respected, because stepping through the useContractCall, I see that useNetwork returns some kind of blank network provider (and remains in that state, so it never initializes).

**Comment by kunalalite** [comment]
I'm facing the same issue. I wanted to add a new network as per documentation, therefore I decided to migrate from 0.6.3 to 0.12.2, but I'm facing issues in reading from the chain using useContractCalls as well as useCalls. Does anyone have a fix regarding it?

**Comment by brunitob** [comment]
Same with 0.12.3

**Comment by RyanRHall** [comment]
Seems like this was fixed in 0.12.4

**Comment by brunitob** [comment]
Working now with 0.12.4 :)
