### ISSUE TITLE
Hooks (useCall & useCalls) not returning data when wallet not connected / wrong network / !window.ethereum

### ISSUE THREAD

**Issue by nickhere432** [TrueFiEng/useDApp#677]
Hooks (useCall & useCalls) not returning data when wallet not connected / wrong network / !window.ethereum. Checking network tab, all RPC calls are 200. 

Steps to reproduce:

1. Disconnect app in metamask if already connected.
2. Refresh app 
3. useCall & useCalls hook returns undefined
or 
1. Open app in incognito tab.
2. useCall & useCalls hook returns undefined

**Comment by dmaretskyi** [comment]
Could you please include a code example?

**Comment by nickhere432** [comment]
> Could you please include a code example?

`function useContractInfo() {
    const { value, error } =
        useCall({
            contract: new Contract(contractAddress, contractInterface),
            method: 'getContractInfo',
            args: []
        }) ?? {};
    if (error) {
        console.error(error.message);
        return {
            totalStaked: undefined,
            totalRefBonus: undefined,
            totalUsers: undefined
        };
    }

    return {
        totalStaked: value?.[0],
        totalRefBonus: value?.[1],
        totalUsers: value?.[2]
    };
}`

**Comment by noobshow** [comment]
> > Could you please include a code example?
> 
> ```
> function useContractInfo() {
>     const { value, error } =
>         useCall({
>             contract: new Contract(contractAddress, contractInterface),
>             method: 'getContractInfo',
>             args: []
>         }) ?? {};
>     if (error) {
>         console.error(error.message);
>         return {
>             totalStaked: undefined,
>             totalRefBonus: undefined,
>             totalUsers: undefined
>         };
>     }
> 
>     return {
>         totalStaked: value?.[0],
>         totalRefBonus: value?.[1],
>         totalUsers: value?.[2]
>     };
> }
> ```

I'm thinking you should use codesandbox.com since the example you posted doesn't have the contractAddress, contractInterface variables defined

**Comment by CasperGhostCrypto** [comment]
Ran into the same issue, Check your config and make sure you're importing `Mainnet.chainId` rather than `Mainnet.chainID`. the Docs need to be updated.

**Comment by aaqibsheikh** [comment]
same issue facing => useCall return value and error undefined.
React: v18
usedapp/core: 1.0.0
ethers: 5.5.x

**Comment by dnilosek** [comment]
Same issue here too.

**Comment by noobshow** [comment]
Same issue as https://github.com/TrueFiEng/useDApp/issues/725#issuecomment-1110230151.
