### ISSUE TITLE
Sending a lot of requests

### ISSUE THREAD

**Issue by FanManutd** [TrueFiEng/useDApp#700]
Hi. It's strange, but every 2-4 seconds a request is sent to infura. All I did was connect the DAPPProvider. Don't know what could be the reason? Or is it ok?
![image](https://user-images.githubusercontent.com/90761929/163814125-d2c941b1-108e-404b-a4ac-41ba42dc82a8.png)
![image](https://user-images.githubusercontent.com/90761929/163814030-8aede76d-2452-4d26-b66e-a45e4068b761.png)

**Comment by liveangela** [comment]
same issue, and most of them mean to call the 'eth_blockNumber' method

**Comment by FanManutd** [comment]
I noticed that this doesn`t happen in version 0.10.1, I didn`t check other versions.

**Comment by dmaretskyi** [comment]
This is normal behaviour. useDapp always keeps queried data up-to-date, so it periodically checks if the a new block was mined.

If the interval is too short you can manually set it on the provider like this (replace the provider URL and chainId with your own):

```typescript
const avaxProvider = new JsonRpcProvider("https://api.avax-test.network/ext/bc/C/rpc")
avaxProvider.pollingInterval = 10_000;

const config: Config = {
  readOnlyChainId: AvalancheTestnet.chainId,
  readOnlyUrls: {
    [AvalancheTestnet.chainId]: avaxProvider
  },
  pollingInterval: 10000,
  notifications: {
    expirationPeriod: 1000,
    checkInterval: 1000
  }
}
```

**Comment by FanManutd** [comment]
> If the interval is too short you can manually set it on the provider like this (replace the provider URL and chainId with your own)

Thank you, it`s help

**Comment by LALauw** [comment]
> This is normal behaviour. useDapp always keeps queried data up-to-date, so it periodically checks if the a new block was mined.
> 
> If the interval is too short you can manually set it on the provider like this (replace the provider URL and chainId with your own):
> 
> ```ts
> const avaxProvider = new JsonRpcProvider("https://api.avax-test.network/ext/bc/C/rpc")
> avaxProvider.pollingInterval = 10_000;
> 
> const config: Config = {
>   readOnlyChainId: AvalancheTestnet.chainId,
>   readOnlyUrls: {
>     [AvalancheTestnet.chainId]: avaxProvider
>   },
>   pollingInterval: 10000,
>   notifications: {
>     expirationPeriod: 1000,
>     checkInterval: 1000
>   }
> }
> ```

Hey, this doesn't seem to work on my end. I've tried it the exact same way but it seems the intervals are the same even with an interval of 100000.
````typescript
const provider = new ethers.providers.JsonRpcProvider(
  "https://cloudflare-eth.com/"
);
provider.pollingInterval = 100000;

const config: Config = {
  readOnlyChainId: Mainnet.chainId,
  readOnlyUrls: {
    [Mainnet.chainId]: "https://cloudflare-eth.com/",
  },
  pollingInterval: 100000,
  notifications: {
    expirationPeriod: 1000,
    checkInterval: 1000,
  },
};
````
