### ISSUE TITLE
Return trasnaction response/error on awaiting

### ISSUE THREAD

**Issue by akim-bow** [TrueFiEng/useDApp#720]
Hello

Example:

I have a function, that should sequentially execute some transactions.

const { send: buyMarketItem, state: buyMarketItemState } = useContractFunction(marketContract, "buyMarketItem");
const { send: applyResult, state: applyResultState } = useContractFunction(marketContract, "applyResult");

My button handler looks like:

const handleClick = () => {
  await buyMarketItem();
  await applyResult();
};

I would like to stop executing second transaction if the first one is failed by throwing error or returning some error object/value;
How could i achieve this? Actually i can give you a PR to fix this issue in my case.

**Comment by JayWelsh** [comment]
You can probably use `buyMarketItemState?.status` to check if it is equal to `'Success'`
