### ISSUE TITLE
`switchNetwork` should return a promise but only returns a void

### ISSUE THREAD

**Issue by alexiskattan** [TrueFiEng/useDApp#743]
Use case is we want to wait for the user to switch networks before going forward.

In the docs (https://usedapp-docs.netlify.app/docs/Guides/Transactions/Switching%20Networks) it looks like `switchNetwork` is supposed to return a promise.  However when we implement it in code, we are only getting a void back.  (e.g. 'await' has no effect on the type of this expression.)

**Comment by gaspardip** [comment]
Types are wrong, it implicitly returns a `Promise` so you can `await` it. TS will complain but you can safely ignore it.
