### ISSUE TITLE
getChainName has been deprecated.  Is there a replacement?

### ISSUE THREAD

**Issue by alexiskattan** [TrueFiEng/useDApp#751]
It looks like `getChainName` has been deprecated.  (https://usedapp-docs.netlify.app/docs/API%20Reference/Helpers#getchainname-deprecated)

I was wondering if there was any replacement for getting the name of the chain given the chainId?  Or is a switch statement the right way to go?

**Comment by rzadp** [comment]
@alexiskattan It can be done like so:

```tsx
const name = DEFAULT_SUPPORTED_CHAINS
  .find((network) => network.chainId === chainId)
  ?.chainName
```

I have added the example to the docs in https://github.com/TrueFiEng/useDApp/pull/752

**Comment by alexiskattan** [comment]
I tried this... the issue was that we are adding in a custom chain which doesn't seem to be picked up by `DEFAULT_SUPPORTED_CHAINS` after it is added.
