### ISSUE TITLE
send should return ethers transaction instead of void

### ISSUE THREAD

**Issue by harmaus** [TrueFiEng/useDApp#757]
const { send } = useContractFunction('erc20', "transfer");

currently `send` promise resolves to the void, but I think it would be more useful on having it on resolving to the ethers transaction response (like state.transaction).
So it could be used instantly after tx is broadcasted. Would be able to use .transaction.wait() for example so I could trigger some action after tx is mined

**Comment by JayWelsh** [comment]
I think you can use this to check if the tx is successful:

```
const { send, state } = useContractFunction('erc20', "transfer");
```

Then you can refer to the value of `state.status` to check if it is equal to 'Success'

But I do agree that it might be better for `send` to return something, or at least there should be a way to extract an error if an error is thrown during `send`.

**Comment by grinry** [comment]
> I think you can use this to check if the tx is successful:
> 
> ```
> const { send, state } = useContractFunction('erc20', "transfer");
> ```
> 
> Then you can refer to the value of `state.status` to check if it is equal to 'Success'

If you want to trigger some action after tx is confirmed you still need to use `useEffect` and watch `state.status`.
And as far as I understand it's against react guidelines how you should use that hook.

**Comment by GeraldHost** [comment]
I agree with this, it would be simple to just return the `receipt` from the `send` function https://github.com/TrueFiEng/useDApp/blob/24e96686816e3881ba5c896a15aa744e1673c0cf/packages/core/src/hooks/useContractFunction.ts#L90
