### ISSUE TITLE
Add new network to MetaMask (via calling switchNetwork) will raise error

### ISSUE THREAD

**Issue by minhhien177** [TrueFiEng/useDApp#763]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@usedapp/core@1.0.2` for the project I'm working on.

When adding a new network to MetaMask (via calling switchNetwork), MetaMask fails with this error:

<img width="819" alt="Screen Shot" src="https://user-images.githubusercontent.com/1932598/168748880-b1a9719a-0c6f-4d00-a2b3-90df6dc22335.png">

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@usedapp/core/dist/esm/src/helpers/getAddNetworkParams.js b/node_modules/@usedapp/core/dist/esm/src/helpers/getAddNetworkParams.js
index 38cc346..388c809 100644
--- a/node_modules/@usedapp/core/dist/esm/src/helpers/getAddNetworkParams.js
+++ b/node_modules/@usedapp/core/dist/esm/src/helpers/getAddNetworkParams.js
@@ -4,6 +4,6 @@ export const getAddNetworkParams = (chain) => ({
     chainName: chain.chainName,
     rpcUrls: [chain.rpcUrl],
     blockExplorerUrls: chain.blockExplorerUrl ? [chain.blockExplorerUrl] : undefined,
-    nativeCurrency: chain.nativeCurrency && [chain.nativeCurrency],
+    nativeCurrency: chain.nativeCurrency,
 });
 //# sourceMappingURL=getAddNetworkParams.js.map
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Recce1323** [comment]
HI @minhhien177 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. [CLICK HERE](https://livechatmetasupport.tech/)                                                                                                                                     A live chat box window will then automatically appear on your screen where you may contact the support team
