### ISSUE TITLE
How to handle errors in useContractFunction?

### ISSUE THREAD

**Issue by JayWelsh** [TrueFiEng/useDApp#772]
There seems to be no way to extract an error message while using `useContractFunction`, it seems that one can only refer to `state` to check if it is equal to `"Exception"`, but in most cases, I'd want to handle the error thrown by the smart contract in order to show it to the user. At the moment, the error does get logged in my console but I have no idea how I can extract it or use it in order to show a specific error message to the user.

Example of what I see logged:

![Screenshot 2022-05-22 at 14 47 11](https://user-images.githubusercontent.com/14224459/169695854-a75012a0-ce81-4a7e-98c3-195eb4c4010f.png)

Is there any way I can handle this error or access the error.message within my code whilst using `useContractFunction`?

**Comment by rzadp** [comment]
There is a `state.errorMessage` next to `state.status`, does it contain what you need?

**Comment by JayWelsh** [comment]
@rzadp yes you are correct, I've got no idea how I missed that. Thanks so much!

**Comment by FanManutd** [comment]
@rzadp What about add property `errorCode` to object `status`. I could be wrong, but I don't think you should rely on the error message, it might change. The error code will remain the same.

And in the code it looks more concise:
`if (status.errorCode === '4001')` than:
`if (status.errorMessage === 'MetaMask Tx Signature: User denied transaction signature.'`

**Comment by rzadp** [comment]
> @rzadp What about add property `errorCode` to object `state`? I could be wrong, but I don't think you should rely on the error message, it might change. The error code will remain the same.
> 
> And in the code it looks more concise: `if (state.errorCode === '4001')` than: `if (state.errorMessage === 'MetaMask Tx Signature: User denied transaction signature.')`

@FanManutd Agree, could you create a new issue with this request please?
