### ISSUE TITLE
useContractFunction state.status is always PendingSignature

### ISSUE THREAD

**Issue by nareshkatta99** [TrueFiEng/useDApp#774]
When we use walletconnect/web3-provider, as provider to `send` a transaction with `useContractFunction` the status of the transaction is always **PendingSignature** even if user _accepts / rejects_ the transaction.

Expected behavior is to either change the state to reflect the same or throw an `Error` to catch.
Current behavior status is **PendingSignature**

**Comment by rzadp** [comment]
What's the version of useDapp you have installed and the version of walletconnect, so we have a possibility of debugging this?

**Comment by nareshkatta99** [comment]
"@usedapp/core": "^1.0.2",
"@walletconnect/web3-provider": "^1.7.8",

**Comment by nareshkatta99** [comment]
I did some testing and found that that issue is not with useDapp or WalletConnect, but with Metamask Mobile App.
Closing the issue here.

**Comment by FanManutd** [comment]
#803
