### ISSUE TITLE
Incorrect estimation of limit gas in transaction

### ISSUE THREAD

**Issue by RetroDefi** [TrueFiEng/useDApp#782]
Apparently the gas buffer system is causing an incorrect estimation of gas limit in transactions of the useContractFunction hook, this error is easily noticeable when wanting to use an NFT creation contract that increases or differs the gas depending on the number of NFTs to be minted .

In version 0.12.9 apparently there is no problem

**Comment by rzadp** [comment]
@RetroDefi What exactly is the nature of the error - wrong amount of gas estimated, or an error when estimating?

**Comment by RyoNkmr** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/17243595/171079128-3859fe14-46f6-4388-9d3d-858b3ab66c2c.png">

out of gas too in Rinkeby testnet

**Comment by RetroDefi** [comment]
@rzadp error when estimating

**Comment by rzadp** [comment]
> @rzadp error when estimating the gas, because not enough gas is estimated for the transaction and it ends up failing

Are your contracts public by any chance, so we could debug?

**Comment by RivetParallel** [comment]
same issue! estimate gas error when send BNB value contract

**Comment by rzadp** [comment]
@RetroDefi @RivetParallel Just to confirm - the error does NOT happen when you do NOT specify buffer limit in the config?

**Comment by RetroDefi** [comment]
> @RetroDefi @RivetParallel Just to confirm - the error does NOT happen when you do NOT specify buffer limit in the config?

It happens in both cases.
