### ISSUE TITLE
It seems that switch network is not available 

### ISSUE THREAD

**Issue by morandalex** [TrueFiEng/useDApp#805]
It seems that switch network is not available 

![image](https://user-images.githubusercontent.com/9484568/172052506-678eb94d-6e09-4481-beb7-4aece6dd52a1.png)

**Comment by rzadp** [comment]
@morandalex Hmm, may I ask which version of usedapp do you have installed?

**Comment by morandalex** [comment]
@usedapp/core": "^0.4.1
