### ISSUE TITLE
Refresh of data still calling even when set to never

### ISSUE THREAD

**Issue by VinHylme** [TrueFiEng/useDApp#819]
I noticed that for patch 1.0.8 there was a change to address the auto refresh issue, I have tried running a useCall for a custom hook that I have written and I am still getting calls made over and over again, I've tried adding the refresh in the config file, in the query param and both at the same time and still the issue persists.

**Comment by mj426382** [comment]
Do you mean blockNumber requests?
Would you prefer to block number not to be refreshed as well?

**Comment by mj426382** [comment]
We thought about adding an option to make whole useDapp static, would this idea fit you?

**Comment by VinHylme** [comment]
@mj426382  that would be great too if also possible to have a refetch function returned on the useCall(s) function to manually trigger them based on a condition or whatnot, is this possible?
