### ISSUE TITLE
Crytical. useDApp rerender all application after 1.0.6?

### ISSUE THREAD

**Issue by FanManutd** [TrueFiEng/useDApp#826]
Hi! I use nextJS with built-in layout feature.
![image](https://user-images.githubusercontent.com/90761929/173795548-28477454-1d22-49d7-833b-b670d3eb2e59.png)

This means that in my project, when changing the page, the layout remains unchanged and only the insides of tabs change. This can be seen by the animation of the blue stripe.
![1](https://user-images.githubusercontent.com/90761929/173793430-161f82a7-318b-4194-bc43-ae29623e275a.gif)

I have experimentally figured out that everything works as expected with `@usedapp/core` 1.0.5. The oddities begin if you upgrade `@usedapp/core` to version 1.0.6 or higher. The application starts to completely re-render, although only the contents of tabs should change. This can be seen in devtools and by the fact that the animation of the blue stripe has disappeared.

![2](https://user-images.githubusercontent.com/90761929/173794137-9ac93bec-a5ed-455b-8375-d7e1ae72115c.gif)

What could have gone wrong in version 1.0.6?

**Comment by FanManutd** [comment]
> Hey @FanManutd , does the issue still persist in version 1.0.9 of useDApp?

1.0.9 fix this! Thank you very much!

**Comment by aofject** [comment]
thank you!!!
