### ISSUE TITLE
useCalls randomly got left out

### ISSUE THREAD

**Issue by JasonHe-da** [TrueFiEng/useDApp#835]
**Describe the bug**
Our project has a custom hooks that will go to different chain id and fetch the data to the frontend. We are using useCalls for each chainid. 
<img width="674" alt="Screen Shot 2022-06-21 at 16 19 27" src="https://user-images.githubusercontent.com/52399371/174912184-bc130a35-33bc-47c7-b308-17967377a69f.png">
![F4F4C948-C35C-4A2F-8273-193997D8886B_4_5005_c](https://user-images.githubusercontent.com/52399371/174912945-297c837b-ddda-473d-b86d-bdd4ff3fd6c8.jpeg)
The issue is sometimes, the useCalls will be left out for specific chain, and in usedapp dev tool, it shows it is not even got called:
correct numbers of call:
![E131B338-177C-4FDB-889B-D11BD2987159](https://user-images.githubusercontent.com/52399371/174912669-bfed98c6-69ff-4194-b798-389ea8047cb0.jpeg)
incorrect numbers of call:
![2B366623-8A3D-4C79-A615-CCBB652E8C89](https://user-images.githubusercontent.com/52399371/174912706-df8863f0-55a3-45f7-a587-7286c54bb0d9.jpeg)
In this case, one of three chains information is not getting called on. 
those calls are never got executed(we have set refresh to 'never').
It happens randomly. 

Does anyone knows why that is happening and how to fix it?

**Software versions**
 - `useDapp` version: 1.0.10

**Comment by yivlad** [comment]
Hey @JasonHe-da , does the issue still persist in the latest version of useDApp (1.0.12)

**Comment by JasonHe-da** [comment]
@yivlad it is still not working: it turns out to be one of three useCalls return undefined for all the data randomly and not even trigger calls in the usedapp dev tool, but if we use useCalls for only one chain, it works just fine

**Comment by mj426382** [comment]
Please read our docs:
https://usedapp-docs.netlify.app/docs/Guides/Transactions/Contract%20Functions

**Comment by mj426382** [comment]
@JasonHe-da can you show us your config?

**Comment by JasonHe-da** [comment]
@mj426382 @yivlad
![7073E291-03B9-499D-985D-DEF5A7ECC944](https://user-images.githubusercontent.com/52399371/175417577-28166f36-fa67-49dd-ba68-7abcf2d481fd.jpeg)

**Comment by yivlad** [comment]
@JasonHe-da I have been trying to reproduce what you were talking about, but unfortunately with no luck. Can you provide minimal reproducible example or some other guidance how to reproduce the bug? (I'm assuming that in config you showed us you deleted `readOnlyUrls` and `mutlicallAddresses`)
