### ISSUE TITLE
support for react native?

### ISSUE THREAD

**Issue by sturmenta** [TrueFiEng/useDApp#846]
useDApp uses window.localStorage, this can be done in react native with AsyncStorage

**Comment by sturmenta** [comment]
For the moment I was able to get the react native app working using this code in the side of `react-native` app on `index.js`

```js
// TODO: check this because are async & in the `useDapp` lib are sync
window = {localStorage: {}};
window.localStorage.setItem = AsyncStorage.setItem;
window.localStorage.removeItem = AsyncStorage.removeItem;
window.localStorage.getItem = AsyncStorage.getItem;

// TODO: check how affect this to the app & try to pass a event dispatcher
document = {};
document.addEventListener = () => {};
```

I will be commenting on further progress here

**Comment by sturmenta** [comment]
<img width="1827" alt="Screen Shot 2022-06-24 at 23 43 17" src="https://user-images.githubusercontent.com/30802967/175755256-c78f131e-4756-401e-a315-0c66da7406f9.png">

**Comment by mj426382** [comment]
Is this the only thing to change to fully supports react native?

**Comment by sturmenta** [comment]
all uses of `window.` should be reviewed as well
