### ISSUE TITLE
Unable to Call Rinkeby Contract Functions

### ISSUE THREAD

**Issue by AydinGokce** [TrueFiEng/useDApp#856]
**Describe the bug**
I'm building an app which is supposed to read from a smart contract on Rinkeby via the useCall hook. 

I've defined my config as follows
```
const config = {
  readOnlyChainId: Rinkeby.chainId,
  readOnlyUrls: {
    [Rinkeby.chainId]: "https://rinkeby.infura.io/v3/" + INFURA_PROJECT_ID,
  },
}
```
and set up the contract call

```
function useNFTInfo(groupId) {

    const provider = new ethers.providers.Web3Provider(window.ethereum)
    const ethContract = new Contract(address, abi, provider)

    console.log("provider: ", provider)

    const { value, error } = useCall({
        contract: ethContract,
        method: "someMethod",
        args: [groupId], 
    })
        ?? {};
    if (error) {
        console.error(error.message)
        return undefined
    } else {
        console.debug(value)
        return value?.[0]
    }
}
```
When I make the contract call, I get this error: 
`Invalid contract call: address=0xf53C2DaA21f1b09936e63442E5cBe76Bd0fE73d9 method=someMethod args=someArg`

I figured out that the cause for the error is that the provider is connected to `localhost:8545`, but I have no idea why or how to fix it. 

I've logged the `provider` object and attached a screenshot below. Note that the connection name is Rinkeby and the ChainId is 4, but the `connection` variable (highlighted) is set to `localhost:8545`.

(you may need to open in a new tab and zoom in)
![Screenshot from 2022-06-29 13-47-45](https://user-images.githubusercontent.com/82673628/176542641-c83d5456-3faa-4159-99c3-474e8ac8cf2b.png)

I was not able to reproduce this error on my other computer. It is identical code, but the contract calls work and the connection says `metamask` instead of `localhost:8545`

**Software versions**
 - `useDapp` (installed version of `@usedapp/core`): 1.0.0
 - Yarn: 1.22.18
 - Node: 16.13.0

**Additional context**
Before attempting to test the contract on Rinkeby, I was testing it on a local Ganache blockchain running on `localhost:8545`. I'm pretty certain that somehow my app or metamask is still configured to listen on that URL. I've tried resetting my account, deleting and re-adding metamask, restarting my browser and clearing cache, to no avail. 

Another interesting thing worth noting is that I used the exact same provider and contract with `useContractFunction`, and that works perfectly. It's just `useCall` that gives the error.

If anyone has any idea as to how I could get my provider to listen correctly on Rinkeby, it would be massively appreciated. I am more than happy to provide additional information upon request.

Thanks!

**Comment by rzadp** [comment]
@AydinGokce Please try to create the contract without the provider.

```
const ethContract = new Contract(address, abi)
```

UseDapp is supposed to use the providers on its own - that's why you provider the infura URL in the config.
Also, just to make sure, because you did not mention it - you made sure to actually switch the network to Rinkeby in MetaMask, right?

Also, for good measure, you can explicitly provide a `chainId` to the `useCall` - try that if it still does not work:

```
useCall({ xxx }, { chainId: Rinkeby.chainId })
```

**Comment by AydinGokce** [comment]
@rzadp Thanks for the response. Creating a contract object without the provider causes this error in the console:

`Uncaught Error: invalid signer or provider (arg="signerOrProvider", value=undefined, version=4.0.49)`

I can also confirm that I am connected to Rinkeby on metamask.

**Comment by rzadp** [comment]
@AydinGokce First of all, could you upgrade `@usedapp/core` to the most recent version, and then we can more effectively look into it?

**Comment by AydinGokce** [comment]
I worked around the issue by uninstalling node-modules and yarn.lock, and re-installing packages with npm.
