### ISSUE TITLE
SwitchNetwork on working on MetaMask moblie

### ISSUE THREAD

**Issue by alexiskattan** [TrueFiEng/useDApp#866]
**Describe the bug**
Trying to use SwitchNetwork on metamask mobile to add the network and switch to it. 

MetaMask moblie is able to autoconfig new networks. We tried adding some stuff from chainlist.org and MetaMask does the right thing.

**Comment by rzadp** [comment]
I have tested it now on useDapp `1.1.5` and MetaMask mobile on iOS - seems to switch properly when executing `switchNetwork`.

<img src="https://user-images.githubusercontent.com/12039224/186141651-eca14851-37fb-42ba-ba20-35db10c1e430.jpg" width="400px"/>

Please reopen with more details if the issue persist on a recent version of useDApp.
