### ISSUE TITLE
Get a balance of my account in Songbird network

### ISSUE THREAD

**Issue by 0xilyad** [TrueFiEng/useDApp#896]
I am trying to get a wallet balance in Songbird network for my dApp, so I used **useEtherBalance** hook function to get it.

But it shows me "undefined". Is there any way to solve this?

**Comment by rzadp** [comment]
@0xHir0 We're could use a little more details.
Can you show your usedapp config? (redacting any secret tokens)

**Comment by 0xilyad** [comment]
Though my wallet is not connected to the website, I have to get value from read functions of the smart contract, but now it's impossible. How can I solve the issue?

**Comment by 0xilyad** [comment]
Can't I use @usedapp/core@1.1.0 on Songbird network?

**Comment by jakvbs** [comment]
Hi, can you please check if it works on current dev version of useDApp: `@usedapp/core@1.2.0-dev.b5d7950`

**Comment by 0xHir0** [comment]
Still doesn't work.

**Comment by jakvbs** [comment]
Can you send your app config and failing code fragment?

**Comment by 0xHir0** [comment]
Can we have a chat on discord?

**Comment by jakvbs** [comment]
Sure, my nickname: `kvba`

**Comment by 0xHir0** [comment]
0xilyad#5555
please DM me

**Comment by 0xHir0** [comment]
This is the config variable.
```javascript
const config = {
  readOnlyChainId: Songbird.chainId,
  multicallAddresses: {
    19: '0x60351436cf80A31EA6C3B261C784d3C127dBD6f1',
    14: ''
  },
};
```

**Comment by 0xHir0** [comment]
![image](https://user-images.githubusercontent.com/86695188/195477526-feb542b1-c966-4ea9-844c-9d4271d4ed80.png)

**Comment by 0xHir0** [comment]
![image](https://user-images.githubusercontent.com/86695188/195477608-55076515-718a-4095-98e4-d230243ff8f7.png)

**Comment by jakvbs** [comment]
I sent you a message yestarday, please check if you received it

**Comment by jakvbs** [comment]
> This is the config variable.
> 
> ```js
> const config = {
>   readOnlyChainId: Songbird.chainId,
>   multicallAddresses: {
>     19: '0x60351436cf80A31EA6C3B261C784d3C127dBD6f1',
>     14: ''
>   },
> };
> ```

Please check this config with latest dev version of useDApp:
```ts
const config = {
  readOnlyChainId: Songbird.chainId,
  readOnlyUrls: {
    [Songbird.chainId]: 'https://songbird.towolabs.com/rpc',
  }
}
```

**Comment by 0xHir0** [comment]
Thanks very much. It works well.
