### ISSUE TITLE
ReadOnly provider while you have connect your wallet

### ISSUE THREAD

**Issue by immunity20** [TrueFiEng/useDApp#903]
Hello, I have provide readOnly provider (paid infura)
So every read method is executed by this provider
As soon as metamask/wallet is connect then metamask provider (free/slow infura) is used
is it possible to force read methods to be serviced from readOnly provider?
and only write methods would use wallet provider?

**Comment by rzadp** [comment]
We are currently working on adding connectors to different wallets including metamask, and we will have on option for the user for configuring whether we would like to use read-connection on his wallet or not.

**Comment by rzadp** [comment]
Also, @immunity20 current implementation should not use the wallet for reading from contracts (except basic stuff like block number or connected account balance). Or do you have reason to think otherwise?

**Comment by immunity20** [comment]
If metamask is turned to mainnet and I try to view the app in Rinkeby.
the read methods will be executed on Mainnet (metamask's current chain)

**Comment by rzadp** [comment]
Yes, the metamask's current chain is used - but the read-only providers are used for reading from that chain.
You can also explicitly add Rinkeby `chainId` to hooks - e.g. `useEtherBalance(address, { chainId: Rinkeby.chainId })`

**Comment by immunity20** [comment]
Thanks for the tip :D !
