### ISSUE TITLE
How to setting ConnectionInfo ?

### ISSUE THREAD

**Issue by yanuar-ar** [TrueFiEng/useDApp#904]
How to setting ConnectionInfo https://docs.ethers.io/v5/api/utils/web/#ConnectionInfo ? 

I have tried this but it didnt work.

```
const config: Config = {
    readOnlyChain: ChainId.Mainnet,
    readOnlyUrls: {
      [ChainId.Mainnet]: 'https://mainnet.infura.io/v3/xxx',
    },
    headers: { 'Content-Type': 'application/json; charset=utf-8' }
  }
    
  ReactDOM.render (
    <React.StrictMode>
      <DAppProvider config={config}>
        <App />
      </DAppProvider>
    </React.StrictMode>,
    document.getElementById('root')
  )
```

**Comment by rzadp** [comment]
This is currently not implemented. What is the use case, or what problem are you trying to solve?

**Comment by yanuar-ar** [comment]
I need change the request header from content-type: text/plain;charset=UTF-8 to application/json . Some RPC node cannot accept  text/plain;charset=UTF-8 and only accept application/json .
Any solution?

**Comment by rzadp** [comment]
@yanuar-ar It should be done like this:

```
readOnlyUrls: {
    [Mainnet.chainId]: new StaticJsonRpcProvider({
      url: 'https://mainnet.infura.io/v3/xxx',
      headers: { 'Content-Type': 'application/json; charset=utf-8' }
    })
},
```

**Comment by yanuar-ar** [comment]
I've tried but

```
import { StaticJsonRpcProvider } from '@ethersproject/providers';

const useDappConfig = {
  readOnlyChainId: TelosChain.chainId,
  readOnlyUrls: {
    [TelosChain.chainId]: new StaticJsonRpcProvider({
      url: 'https://mainnet.telos.net/evm',
      headers: { 'Content-Type': 'application/json; charset=utf-8' }
    })
  },
  networks: [TelosChain]
};

error:

```
> Type '{ readOnlyChainId: number; readOnlyUrls: { [x: number]: StaticJsonRpcProvider; }; networks: Chain[]; }' is not assignable to type 'Partial<FullConfig>'.
>   Types of property 'readOnlyUrls' are incompatible.
>     Type '{ [x: number]: StaticJsonRpcProvider; }' is not assignable to type 'NodeUrls'.
>       'number' index signatures are incompatible.
>         Type 'StaticJsonRpcProvider' is not assignable to type 'string'

**Comment by rzadp** [comment]
@yanuar-ar You might have to upgrade your version of usedapp
