### ISSUE TITLE
useCall(s) stops working until F5 refresh after failed multicall

### ISSUE THREAD

**Issue by joshlang** [TrueFiEng/useDApp#913]
Occasionally, an provider's API (usually fantom lol) returns a result which creates an unhandled exception in `multicall`.

Sometimes it happens in just a couple minutes.  Sometimes, hours.

As soon as that happens, all `useCall` and `useCalls` stop working in the entire app until a F5 refresh.

Here's what shows up in console (fastMulticallEncoding = true or false, the error is the same)
```
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
provider.tsx:83 Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xdc85396592f0F466224390771C861EE3957a3ff4","data":"LOTS OF DATA HERE","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":209,\"error\":{\"code\":-32000,\"message\":\"header not found\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xdc85396592f0f466224390771c861ee3957a3ff4\",\"data\":\"LOTS OF DATA HERE\"},\"0x29fdd5c\"],\"id\":209,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.ankr.com/fantom/"}, code=CALL_EXCEPTION, version=providers/5.6.8)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at checkError (json-rpc-provider.ts:66:1)
    at StaticJsonRpcProvider.<anonymous> (json-rpc-provider.ts:603:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:1:1)
(anonymous) @ provider.tsx:83
(anonymous) @ performMulticall.ts:41
Promise.catch (async)
performMulticall @ performMulticall.ts:39
multicallForChain @ provider.tsx:97
(anonymous) @ provider.tsx:115
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

Network calls *ARE* still being made a couple times a minute, just as before.

useDapp: 1.1.3 (latest)

Probably related: #742

**Comment by joshlang** [comment]
Here's a sample console dump from a live app (in other words, built with env = production)

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x41263cBA59EB80dC200F3E2544eda4ed6A90E76C","data":"LOTS OF DATA HERE","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":72,\"error\":{\"code\":-32000,\"message\":\"missing trie node 134a925515fc0f385e9e0de8d842f4311289a40a4dcbc1813d0e3bb5b8d0b7b0 (path )\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x41263cba59eb80dc200f3e2544eda4ed6a90e76c\",\"data\":\"LOTS OF DATA HERE\"},\"0x1325d05\"],\"id\":72,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://bsc-dataseed3.binance.org/"}, code=CALL_EXCEPTION, version=providers/5.6.8)
    at e.value (index.ts:261:28)
    at e.value (index.ts:273:20)
    at Do (json-rpc-provider.ts:66:16)
    at f.<anonymous> (json-rpc-provider.ts:603:20)
    at l (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at o (base-provider.ts:702:35)
```

**Comment by joshlang** [comment]
This one is possibly unrelated to the issues above (where the RPC returns a response which crashes useDapp functionality).  

But it *ALSO* crashes useDapp and requires F5 reload.

It would be helpful if useDapp could recover from errors in general, instead of just exploding the entire app.

For this one, I'll just turn off fast multicall encoding, as it's experimental - but still... stop crashing plz :)

```
provider.tsx:83 Error: Invalid calldata
    at fail (common.ts:11:1)
    at decodeAggregate (decoder.ts:15:1)
    at fastEncodingMulticall (multicall.ts:56:1)
(anonymous) @ provider.tsx:83
(anonymous) @ performMulticall.ts:41
Promise.catch (async)
performMulticall @ performMulticall.ts:39
multicallForChain @ provider.tsx:97
(anonymous) @ provider.tsx:115
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

**Comment by VinHylme** [comment]
also experiencing this issue

**Comment by joshlang** [comment]
Just confirming this issue still occurs with `1.1.4`

And here's another sample error, which, like all the others, crashes useDapp functionality entirely until F5.

```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="aggregate((address,bytes)[])", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at Interface.decodeFunctionResult (interface.ts:427:1)
    at Contract.<anonymous> (index.ts:400:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:1:1)
overrideMethod	@	react_devtools_backend.js:4026
(anonymous)	@	provider.tsx:83
(anonymous)	@	performMulticall.ts:41
Promise.catch (async)		
performMulticall	@	performMulticall.ts:39
multicallForChain	@	provider.tsx:97
(anonymous)	@	provider.tsx:115
commitHookEffectListMount	@	react-dom.development.js:23150
commitPassiveMountOnFiber	@	react-dom.development.js:24926
commitPassiveMountEffects_complete	@	react-dom.development.js:24891
commitPassiveMountEffects_begin	@	react-dom.development.js:24878
commitPassiveMountEffects	@	react-dom.development.js:24866
flushPassiveEffectsImpl	@	react-dom.development.js:27039
flushPassiveEffects	@	react-dom.development.js:26984
(anonymous)	@	react-dom.development.js:26769
workLoop	@	scheduler.development.js:266
flushWork	@	scheduler.development.js:239
performWorkUntilDeadline	@	scheduler.development.js:533
```

**Comment by rzadp** [comment]
Is this happening with multicall version 1 or 2?

**Comment by rzadp** [comment]
> Sometimes it happens in just a couple minutes. Sometimes, hours.

Does anyone have some way of reproducing this in a consistent way?
I would like to debug it but it's not possible if I cannot make the error happen.

I've experimented with a regular revert of one call (a function that does `revert()` or `require(false)` on-chain), but everything seems to work as expected - other hooks still work if it's multicall v2, and other hooks continue to work after the faulty call is removed, including with multicall v1.

**Comment by joshlang** [comment]
I made a reproduceable version for you.  The problem isn't what I thought.  `useCall` indeed seems to keep working.  However, `{ chainId }` from `useEthers()` is actually what stops working.

The problem occurs only when 2 or more networks are being used at once.

I also noticed that excessive numbers of duplicate calls to `eth_chainId`,  `eth_blockNumber` and `eth_call` are being made.  2, 3, or 4 duplicate calls at a time.  This is a separate issue that might need to be fixed.

Here's a reproduceable version

1) Clone this:  https://github.com/joshlang/usedapp-death
2) Have metamask, and connect to `Binance` or `Fantom` networks
3) `node api.js` to start the localhost rpc server
4) `npm run start` to start the web app

Once you're connected, you should see `Currently connected to account '[YOUR ADDRESS]' on chainId=250` (or chainId=56)

`Local supply: ` will be a number that increments once per `eth_call`

At this point, everything works as expected.

Now:  `ctrl-c` on the local API server running `node api.js` ...

The next `eth_call` will fail, an error is printed in console... and importantly, the `Currently connected to...` line will have the `chainId=` blanked out!  Disconnecting and connecting does not help.  An F5 Refresh is necessary.

Relevant files:
- `/src/index.tsx` defines the local networks...
- `/src/App.tsx` makes the calls, etc
- `/api.js` is the expressjs app which serves localhost rpc calls pretending to be an ethereum network

In `App.tsx` if you comment out line 14 and 15 (so that useCall is only used on one chainId), the problem no longer occurs.

**Comment by rzadp** [comment]
@joshlang Awesome, I'll be looking into it.

**Comment by rzadp** [comment]
@joshlang I have been able to reproduce the issue with your instructions, kudos for the detailed writeup.
I will continue to look into it.

**Comment by joshlang** [comment]
Holy moly, that's great news and super fast

Thanks :)

**Comment by rzadp** [comment]
@joshlang You can check `@usedapp/core@1.1.5-dev.368e2a6` which contains the fix.
I have tested it out in https://github.com/joshlang/usedapp-death and `chainId` no longer disappears.
Hopefully that fixes the issue.

> I also noticed that excessive numbers of duplicate calls to eth_chainId, eth_blockNumber and eth_call are being made. 2, 3, or 4 duplicate calls at a time. This is a separate issue that might need to be fixed.

I noticed it as well - I will take a look at it separately.

**Comment by rzadp** [comment]
Little bit of profiling/optimising has been done in https://github.com/TrueFiEng/useDApp/pull/922
Additional reports of inefficiencies are always welcome.

**Comment by ShynRou** [comment]
I had the same problem with it. 
@rzadp using `@usedapp/core@1.1.5-dev.368e2a6` fixed it for me. Thank you :+1:
