### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by vm06007** [TrueFiEng/useDApp#929]
- Currently `useEtherBalance` allows to specify chainId to fetch ether balance on multiple networks and display to user. 

- Asking / requesting if the same is possible for useCall or other hooks so that by passing chainId could fetch data from a contract on 2 different chains (currently if user has not connected wallet the call always default to the `readOnlyChainId` described in the config. 

Is there a way to display contract data from two different networks?

**Comment by vm06007** [comment]
```
    const { value, error } = useCall(tokenAddress && {
        contract: new Contract(
            tokenAddress,
            ERC20Interface
        ),
        method: "totalSupply",
        args: [],
    }, {chainId: 10000}) ?? {}

    if (error) {
        console.error(error.message);
        return undefined;
    }

    return value?.[0];

```

is this correct?

**Comment by rzadp** [comment]
@vm06007 Yes, that looks correct.
Keep in mind you have to have the corresponding chain configured in readOnlyChainUrls of your useDApp config.
