### ISSUE TITLE
[Feature Request] Update balance

### ISSUE THREAD

**Issue by cwagner22** [TrueFiEng/useDApp#930]
`useEtherBalance` never seems to update the balance.
The problem is there is a Transfer button in my app, which then should decrease the displayed balance once done. What is the recommended way to show the updated balance?

**Comment by rzadp** [comment]
@cwagner22 It should update, so maybe there is some problem of misconfiguration.

1. Does the value update correctly after you refresh the page or open it again in new tab?
2. Do you have maybe `refresh` parameter configured in your useDApp config?

**Comment by Xzirez** [comment]
Hi @rzadp,

If I understand you correctly the solution if we want to implement a "subscription" for the balance is:

- We change the config file to include an `everyBlock` parameter, which will refresh on every x block that gets created.

If this is correct my follow-up question would be - is this not resource extensive? Given that the confirmation rate on the polygon can be around 2 seconds. 

What I would rather do in our specific scenario is to:

- Wait for the transaction to be processed, then subtract a given amount from the user's cached balance.

Let me know if am mistaken and there are in fact no resource issues with the `refresh` option outlined above.

**Comment by cwagner22** [comment]
Thanks, I wasn't aware of `refresh: 'everyBlock'` but I had another issue in my code preventing the balance update.

**Comment by rzadp** [comment]
@cwagner22 Awesome.
If it's feasible, feel free to share the issue you had and the solution, maybe it could help others.
