### ISSUE TITLE
Incorrect estimation of the gas limit, when wanting to execute an external function in a contract

### ISSUE THREAD

**Issue by RetroDefi** [TrueFiEng/useDApp#936]
Describe the bug
Apparently in useDapp, when wanting to execute an external function in a smart contract, it incorrectly estimates the gas limit, causing the transaction to be rejected due to insufficient gas.

To Reproduce
It can be easily reproduced with a contract similar to this one that is deployed on BSC Mainnet which is a pancake yield farm strategy.

https://bscscan.com/address/0x45014e81a703dadDe911a91256c7718809fe448D#writeContract

you can generate the action button in the "Earn" function and verify the gas that is proposed in the metamask wallet, then try to generate the same transaction in the "Earn" function on the bscscan website and verify the gas proposed in the metamask wallet, noting in a simple way that the gas proposed by a website that uses UseDapp will be showing a lower gas limit causing the transaction to be rejected

Software versions

useDapp version 1.1.5
Package manager is NPM
Node version 16.11.1
Additional context

![181702761-97092001-08ce-4c63-8864-aba24cebffdd](https://user-images.githubusercontent.com/82356199/185523026-f78a5144-a3e5-42a4-9201-7dd6d517efb4.png)
![181702759-932093e5-ea82-4194-aa5a-0de4cd51f988](https://user-images.githubusercontent.com/82356199/185523031-21c43c56-87d9-400f-b6ae-483c469b762b.png)

**Comment by RetroDefi** [comment]
The problem continues despite the fact that this bug has been marked as solved, although you can actually use a "gasLimit" by adjusting it manually, the most advisable thing would be for ethers to do it automatically,

*NOTE, the problem started to appear after adding the limit gas buffer

**Comment by JCaraballo113** [comment]
This issue is actually more widespread than you think. See here: https://github.com/TrueFiEng/useDApp/issues/931

**Comment by rzadp** [comment]
@RetroDefi I am trying to repro it. Do you maybe have a similar contract on a testnet that fails, so I can try it out?

**Comment by RetroDefi** [comment]
> @RetroDefi I am trying to repro it. Do you maybe have a similar contract on a testnet that fails, so I can try it out?
> 
> I have been unsuccessful in trying to reproduce the issue so far: [#931 (comment)](https://github.com/TrueFiEng/useDApp/issues/931#issuecomment-1220913721)

Understood, I will try to create a contract as quickly as possible so that it can be replicated in testnet, I just did a clean installation of dependencies and apparently it did not happen again with the mainnet contract in which I showed that the problem appeared.

Please do not close the thread yet, until we test more on testnet and see that usedapp works in various scenarios  ;)

**Comment by rzadp** [comment]
Not closing until we are absolutely sure everything works properly.

**Comment by RetroDefi** [comment]
> Not closing until we are absolutely sure everything works properly.

Hello , sorry for the delay in updating , until now I could not replicate it apparently UseDapp works perfectly when estimating the gas again
