### ISSUE TITLE
Polygon Mumbai not add to Metamask

### ISSUE THREAD

**Issue by alexbakers** [TrueFiEng/useDApp#945]
```
<Button
  colorScheme="gray"
  onClick={async () => {
    if (chainId !== Mumbai.chainId) {
      await switchNetwork(Mumbai.chainId);
      activateBrowserWallet();
    } else {
      activateBrowserWallet();
    }
  }}
>
  Connect
</Button>
```

<img width="421" alt="image" src="https://user-images.githubusercontent.com/98721968/186295488-86ccf47a-654e-414c-9728-2984c4a6eb07.png">

**Comment by mingxin-yang** [comment]
I also encountered this problem when adding mumbai, I was wondering if I could modify the code like this
```
if (chain?.rpcUrl) {
            await provider.send('wallet_addEthereumChain', [getAddNetworkParams(chain)])
        }else{
          throw error
        }
```
You can also throw error when there is no `rpcUrl` or no `chain`, and then you can add it custom, or is there any good method, because my mumbai uses [this method] (https://wiki.polygon.technology /docs/develop/alchemy/#step-11-connect-metamask--alchemy-to-your-project) add, I want to customize

**Comment by mingxin-yang** [comment]
@rzadp

**Comment by mingxin-yang** [comment]
@alexbakers Hello, how did you solve this problem now, because there is no release npm yet

**Comment by rzadp** [comment]
> I also encountered this problem when adding mumbai, I was wondering if I could modify the code like this
> 
> ```
> if (chain?.rpcUrl) {
>             await provider.send('wallet_addEthereumChain', [getAddNetworkParams(chain)])
>         }else{
>           throw error
>         }
> ```

We have change the code in line with your suggestion here:

https://github.com/TrueFiEng/useDApp/blob/8278dad97a8bb07b038e7b618f6b3a914807674c/packages/core/src/providers/network/connectors/connectorController.ts#L140-L143

> because there is no release npm yet

We're not in a rush for a release at the moment before we straighten out some matters related to connectors.\
In the meantime, you can use the `dev` tag from npm. It is released on every commit to `master`.
Current one is `@usedapp/core@1.2.0-dev.e49e437`
