### ISSUE TITLE
provider.getSigner() not a function

### ISSUE THREAD

**Issue by mingxin-yang** [TrueFiEng/useDApp#957]
```
import { DAppProvider } from '@usedapp/core'

import { Goerli, useEthers, useLookupAddress } from '@usedapp/core'
import { getDefaultProvider } from 'ethers'

export const config = {
  readOnlyChainId: Goerli.chainId,
  readOnlyUrls: {
    [Goerli.chainId]: getDefaultProvider('goerli'),
  },
}
<DAppProvider config={config}>
</DAppProvide>

const { active, account, library } = useEthers()

const provider = library;
provider.getSigner()
```

when I use  
```
readOnlyChainId: ChainId.Localhost,
    readOnlyUrls: {
      [ChainId.Localhost]: 'http://127.0.0.1:8545',
    },
```
localhost, provider.getSigner() is work, but after change to goerli, it' became to error.

**Comment by Mijail-Piekarz** [comment]
Same problem here using any local network

**Comment by mingxin-yang** [comment]
@jakvbs Hello, I solved this problem now, I changed `getDefaultProvider('goerli')` to the `url `obtained from` alchemyapi` and it will not put this error

**Comment by jakvbs** [comment]
Hi @mingxin-yang, I found the source of this problem. Method `getDefaultProvider` returns `FallbackProvider` that has not method `getSigner` and in first render this provider is used as `library` returned from `useEthers` hook, then if using Metamask wallet, `Web3Provider` which extends `JsonRpcProvider`  is set. Currently `FallbackProvider` is casted in useDApp to `JsonRpcProvider` type which has this method. It can be confusing, so we're going te make these types more specific.
