### ISSUE TITLE
Connectors were not found in '@usedapp/core'

### ISSUE THREAD

**Issue by longnd1003** [TrueFiEng/useDApp#968]
**Describe the bug**

**To Reproduce**
Specify the config:
```
import { DAppProvider, Polygon, MetamaskConnector, CoinbaseWalletConnector } from '@usedapp/core'

const config = {
  readOnlyChainId: Polygon.chainId,
  readOnlyUrls: {
    [Polygon.chainId]: 'https://polygon-rpc.com'
  },
  networks: [Polygon],
  noMetamaskDeactivate: true,
  connectors: {
    metamask: new MetamaskConnector(),
    coinbase: new CoinbaseWalletConnector()
  }
}
```

**Software versions**
 - `useDapp` version (installed version of `@usedapp/core`); 1.1.5
 - Package manager: yarn
 - Node version: 16.17.0

**Additional context**

The connectors could not be found in installed node_modules with errors:
```
export 'MetamaskConnector' (imported as 'MetamaskConnector') was not found in '@usedapp/core'
export 'CoinbaseWalletConnector' (imported as 'CoinbaseWalletConnector') was not found in '@usedapp/core'
```

**Comment by rzadp** [comment]
Thanks for the report.
Connectors will be available in the next release - `1.2.0`.
I am clarify it in the docs now, sorry for the mixup.
