### ISSUE TITLE
Can't get input error and loading state from useCall hook

### ISSUE THREAD

**Issue by npetridis** [TrueFiEng/useDApp#987]
**Describe the bug**

I cannot know when useCall is loading or when I have an input error when using useCall (e.g. invalid address)

**To Reproduce**
Steps to reproduce the behavior, or a link to repository if public.
At a minimum, please provide your usedapp Config object.
Include information about chains you are connecting to, browser wallets you are using, and anything else that might be relevant.

I am using useCall like this
```
methodCallResult = useCall(contractAddress && allowMethodCall && {
  contract: new Contract(contractAddress, contractInterface),
  method: name,
  args: argsArray
}) ?? {}
```
A button click changes `allowMethodCall` to true so that the contract method is called

The problems are:
If my contract input is correct then`methodCallResult` will change from `{}` to `{value: []}, error: undefined}`
but if my input is not correct (e.g. invalid address input) then I only get a console.warn and I have no way to access the underlying error, also I cannot show and hide a loader or something because I have no data to understand what went wrong or is still fetching data
![Screenshot 2022-09-26 at 16 29 52](https://user-images.githubusercontent.com/6136507/192289715-1eb9e5db-601e-4b4e-9656-45aeab653f5f.png)

```
const config = {
  readOnlyChainId: Mainnet.chainId,
  readOnlyUrls: {
    [Mainnet.chainId]: getDefaultProvider('mainnet'),
    [Goerli.chainId]: getDefaultProvider('goerli'),
  },
};
```

**Software versions**
 - `useDapp` version (installed version of `@usedapp/core`)
 `"@usedapp/core": "~1.1.5"`
 - Package manager (yarn, npm, or pnpm?)
`npm`
 - Node version (`node --version`)
 `v16.15.1`

Thank you!

**Comment by jakvbs** [comment]
I reproduced your problem and it seems it really shouldn't work that way. We're going to discuss the possibilities of fixing it and probably going to add it in the `useDApp@1.2.0` release
