### ISSUE TITLE
NEXTJS: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by gonghaibo** [TrueFiEng/useDApp#989]
**Describe the bug**
When I use useDapp in nextjs everything becomes abnormal

**To Reproduce**
![image](https://user-images.githubusercontent.com/36252719/192740657-7f3482d8-6c0e-48f5-986f-538a6c6ca341.png)
![image](https://user-images.githubusercontent.com/36252719/192740765-18f96ef3-98fb-4fea-bb6d-0539bd707be7.png)

**Software versions**
 - `useDapp`  1.1.5
 - Package manager : yarn 
 - Node version  16.17 LTS

**Additional context**

- Add any other context about the problem here
- Include screenshoots if applicable

**Comment by rzadp** [comment]
@gonghaibo Please try to change your imports - `import x from '@usedapp/core'`, do not use `/dist`
